/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BSky.Client.OpenAPIDateConverter;

namespace BSky.Model
{
    /// <summary>
    /// AppBskyEmbedImagesImage
    /// </summary>
    [DataContract(Name = "app.bsky.embed.images.image")]
    public partial class AppBskyEmbedImagesImage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppBskyEmbedImagesImage" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AppBskyEmbedImagesImage() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AppBskyEmbedImagesImage" /> class.
        /// </summary>
        /// <param name="image">image (required).</param>
        /// <param name="alt">Alt text description of the image, for accessibility. (required).</param>
        /// <param name="aspectRatio">aspectRatio.</param>
        public AppBskyEmbedImagesImage(System.IO.Stream image = default(System.IO.Stream), string alt = default(string), AppBskyEmbedDefsAspectRatio aspectRatio = default(AppBskyEmbedDefsAspectRatio))
        {
            // to ensure "image" is required (not null)
            if (image == null)
            {
                throw new ArgumentNullException("image is a required property for AppBskyEmbedImagesImage and cannot be null");
            }
            this.Image = image;
            // to ensure "alt" is required (not null)
            if (alt == null)
            {
                throw new ArgumentNullException("alt is a required property for AppBskyEmbedImagesImage and cannot be null");
            }
            this.Alt = alt;
            this.AspectRatio = aspectRatio;
        }

        /// <summary>
        /// Gets or Sets Image
        /// </summary>
        [DataMember(Name = "image", IsRequired = true, EmitDefaultValue = true)]
        public System.IO.Stream Image { get; set; }

        /// <summary>
        /// Alt text description of the image, for accessibility.
        /// </summary>
        /// <value>Alt text description of the image, for accessibility.</value>
        [DataMember(Name = "alt", IsRequired = true, EmitDefaultValue = true)]
        public string Alt { get; set; }

        /// <summary>
        /// Gets or Sets AspectRatio
        /// </summary>
        [DataMember(Name = "aspectRatio", EmitDefaultValue = false)]
        public AppBskyEmbedDefsAspectRatio AspectRatio { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AppBskyEmbedImagesImage {\n");
            sb.Append("  Image: ").Append(Image).Append("\n");
            sb.Append("  Alt: ").Append(Alt).Append("\n");
            sb.Append("  AspectRatio: ").Append(AspectRatio).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Image (System.IO.Stream) maxLength
            if (this.Image != null && this.Image.Length > 1000000)
            {
                yield return new ValidationResult("Invalid value for Image, length must be less than 1000000.", new [] { "Image" });
            }

            yield break;
        }
    }

}
