/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BSky.Client.OpenAPIDateConverter;

namespace BSky.Model
{
    /// <summary>
    /// AppBskyVideoGetJobStatus200Response
    /// </summary>
    [DataContract(Name = "app_bsky_video_getJobStatus_200_response")]
    public partial class AppBskyVideoGetJobStatus200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppBskyVideoGetJobStatus200Response" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AppBskyVideoGetJobStatus200Response() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AppBskyVideoGetJobStatus200Response" /> class.
        /// </summary>
        /// <param name="jobStatus">jobStatus (required).</param>
        public AppBskyVideoGetJobStatus200Response(AppBskyVideoDefsJobStatus jobStatus = default(AppBskyVideoDefsJobStatus))
        {
            // to ensure "jobStatus" is required (not null)
            if (jobStatus == null)
            {
                throw new ArgumentNullException("jobStatus is a required property for AppBskyVideoGetJobStatus200Response and cannot be null");
            }
            this.JobStatus = jobStatus;
        }

        /// <summary>
        /// Gets or Sets JobStatus
        /// </summary>
        [DataMember(Name = "jobStatus", IsRequired = true, EmitDefaultValue = true)]
        public AppBskyVideoDefsJobStatus JobStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AppBskyVideoGetJobStatus200Response {\n");
            sb.Append("  JobStatus: ").Append(JobStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
