/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BSky.Client.OpenAPIDateConverter;

namespace BSky.Model
{
    /// <summary>
    /// AppBskyLabelerDefsLabelerViewDetailed
    /// </summary>
    [DataContract(Name = "app.bsky.labeler.defs.labelerViewDetailed")]
    public partial class AppBskyLabelerDefsLabelerViewDetailed : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppBskyLabelerDefsLabelerViewDetailed" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AppBskyLabelerDefsLabelerViewDetailed() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AppBskyLabelerDefsLabelerViewDetailed" /> class.
        /// </summary>
        /// <param name="uri">uri (required).</param>
        /// <param name="cid">cid (required).</param>
        /// <param name="creator">creator (required).</param>
        /// <param name="policies">policies (required).</param>
        /// <param name="likeCount">likeCount.</param>
        /// <param name="viewer">viewer.</param>
        /// <param name="indexedAt">indexedAt (required).</param>
        /// <param name="labels">labels.</param>
        public AppBskyLabelerDefsLabelerViewDetailed(string uri = default(string), string cid = default(string), AppBskyActorDefsProfileView creator = default(AppBskyActorDefsProfileView), AppBskyLabelerDefsLabelerPolicies policies = default(AppBskyLabelerDefsLabelerPolicies), int likeCount = default(int), AppBskyLabelerDefsLabelerViewerState viewer = default(AppBskyLabelerDefsLabelerViewerState), DateTime indexedAt = default(DateTime), List<ComAtprotoLabelDefsLabel> labels = default(List<ComAtprotoLabelDefsLabel>))
        {
            // to ensure "uri" is required (not null)
            if (uri == null)
            {
                throw new ArgumentNullException("uri is a required property for AppBskyLabelerDefsLabelerViewDetailed and cannot be null");
            }
            this.Uri = uri;
            // to ensure "cid" is required (not null)
            if (cid == null)
            {
                throw new ArgumentNullException("cid is a required property for AppBskyLabelerDefsLabelerViewDetailed and cannot be null");
            }
            this.Cid = cid;
            // to ensure "creator" is required (not null)
            if (creator == null)
            {
                throw new ArgumentNullException("creator is a required property for AppBskyLabelerDefsLabelerViewDetailed and cannot be null");
            }
            this.Creator = creator;
            // to ensure "policies" is required (not null)
            if (policies == null)
            {
                throw new ArgumentNullException("policies is a required property for AppBskyLabelerDefsLabelerViewDetailed and cannot be null");
            }
            this.Policies = policies;
            this.IndexedAt = indexedAt;
            this.LikeCount = likeCount;
            this.Viewer = viewer;
            this.Labels = labels;
        }

        /// <summary>
        /// Gets or Sets Uri
        /// </summary>
        [DataMember(Name = "uri", IsRequired = true, EmitDefaultValue = true)]
        public string Uri { get; set; }

        /// <summary>
        /// Gets or Sets Cid
        /// </summary>
        [DataMember(Name = "cid", IsRequired = true, EmitDefaultValue = true)]
        public string Cid { get; set; }

        /// <summary>
        /// Gets or Sets Creator
        /// </summary>
        [DataMember(Name = "creator", IsRequired = true, EmitDefaultValue = true)]
        public AppBskyActorDefsProfileView Creator { get; set; }

        /// <summary>
        /// Gets or Sets Policies
        /// </summary>
        [DataMember(Name = "policies", IsRequired = true, EmitDefaultValue = true)]
        public AppBskyLabelerDefsLabelerPolicies Policies { get; set; }

        /// <summary>
        /// Gets or Sets LikeCount
        /// </summary>
        [DataMember(Name = "likeCount", EmitDefaultValue = false)]
        public int LikeCount { get; set; }

        /// <summary>
        /// Gets or Sets Viewer
        /// </summary>
        [DataMember(Name = "viewer", EmitDefaultValue = false)]
        public AppBskyLabelerDefsLabelerViewerState Viewer { get; set; }

        /// <summary>
        /// Gets or Sets IndexedAt
        /// </summary>
        [DataMember(Name = "indexedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime IndexedAt { get; set; }

        /// <summary>
        /// Gets or Sets Labels
        /// </summary>
        [DataMember(Name = "labels", EmitDefaultValue = false)]
        public List<ComAtprotoLabelDefsLabel> Labels { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AppBskyLabelerDefsLabelerViewDetailed {\n");
            sb.Append("  Uri: ").Append(Uri).Append("\n");
            sb.Append("  Cid: ").Append(Cid).Append("\n");
            sb.Append("  Creator: ").Append(Creator).Append("\n");
            sb.Append("  Policies: ").Append(Policies).Append("\n");
            sb.Append("  LikeCount: ").Append(LikeCount).Append("\n");
            sb.Append("  Viewer: ").Append(Viewer).Append("\n");
            sb.Append("  IndexedAt: ").Append(IndexedAt).Append("\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // LikeCount (int) minimum
            if (this.LikeCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for LikeCount, must be a value greater than or equal to 0.", new [] { "LikeCount" });
            }

            yield break;
        }
    }

}
