/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BSky.Client.OpenAPIDateConverter;

namespace BSky.Model
{
    /// <summary>
    /// A grab bag of state that&#39;s specific to the bsky.app program. Third-party apps shouldn&#39;t use this.
    /// </summary>
    [DataContract(Name = "app.bsky.actor.defs.bskyAppStatePref")]
    public partial class AppBskyActorDefsBskyAppStatePref : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppBskyActorDefsBskyAppStatePref" /> class.
        /// </summary>
        /// <param name="activeProgressGuide">activeProgressGuide.</param>
        /// <param name="queuedNudges">queuedNudges.</param>
        public AppBskyActorDefsBskyAppStatePref(AppBskyActorDefsBskyAppProgressGuide activeProgressGuide = default(AppBskyActorDefsBskyAppProgressGuide), List<string> queuedNudges = default(List<string>))
        {
            this.ActiveProgressGuide = activeProgressGuide;
            this.QueuedNudges = queuedNudges;
        }

        /// <summary>
        /// Gets or Sets ActiveProgressGuide
        /// </summary>
        [DataMember(Name = "activeProgressGuide", EmitDefaultValue = false)]
        public AppBskyActorDefsBskyAppProgressGuide ActiveProgressGuide { get; set; }

        /// <summary>
        /// Gets or Sets QueuedNudges
        /// </summary>
        [DataMember(Name = "queuedNudges", EmitDefaultValue = false)]
        public List<string> QueuedNudges { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AppBskyActorDefsBskyAppStatePref {\n");
            sb.Append("  ActiveProgressGuide: ").Append(ActiveProgressGuide).Append("\n");
            sb.Append("  QueuedNudges: ").Append(QueuedNudges).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
