/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BSky.Client.OpenAPIDateConverter;

namespace BSky.Model
{
    /// <summary>
    /// AppBskyGraphGetStarterPack200Response
    /// </summary>
    [DataContract(Name = "app_bsky_graph_getStarterPack_200_response")]
    public partial class AppBskyGraphGetStarterPack200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppBskyGraphGetStarterPack200Response" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AppBskyGraphGetStarterPack200Response() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AppBskyGraphGetStarterPack200Response" /> class.
        /// </summary>
        /// <param name="starterPack">starterPack (required).</param>
        public AppBskyGraphGetStarterPack200Response(AppBskyGraphDefsStarterPackView starterPack = default(AppBskyGraphDefsStarterPackView))
        {
            // to ensure "starterPack" is required (not null)
            if (starterPack == null)
            {
                throw new ArgumentNullException("starterPack is a required property for AppBskyGraphGetStarterPack200Response and cannot be null");
            }
            this.StarterPack = starterPack;
        }

        /// <summary>
        /// Gets or Sets StarterPack
        /// </summary>
        [DataMember(Name = "starterPack", IsRequired = true, EmitDefaultValue = true)]
        public AppBskyGraphDefsStarterPackView StarterPack { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AppBskyGraphGetStarterPack200Response {\n");
            sb.Append("  StarterPack: ").Append(StarterPack).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
