/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BSky.Client.OpenAPIDateConverter;

namespace BSky.Model
{
    /// <summary>
    /// The subject&#39;s followers whom you also follow
    /// </summary>
    [DataContract(Name = "app.bsky.actor.defs.knownFollowers")]
    public partial class AppBskyActorDefsKnownFollowers : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppBskyActorDefsKnownFollowers" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AppBskyActorDefsKnownFollowers() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AppBskyActorDefsKnownFollowers" /> class.
        /// </summary>
        /// <param name="count">count (required).</param>
        /// <param name="followers">followers (required).</param>
        public AppBskyActorDefsKnownFollowers(int count = default(int), List<AppBskyActorDefsProfileViewBasic> followers = default(List<AppBskyActorDefsProfileViewBasic>))
        {
            this.Count = count;
            // to ensure "followers" is required (not null)
            if (followers == null)
            {
                throw new ArgumentNullException("followers is a required property for AppBskyActorDefsKnownFollowers and cannot be null");
            }
            this.Followers = followers;
        }

        /// <summary>
        /// Gets or Sets Count
        /// </summary>
        [DataMember(Name = "count", IsRequired = true, EmitDefaultValue = true)]
        public int Count { get; set; }

        /// <summary>
        /// Gets or Sets Followers
        /// </summary>
        [DataMember(Name = "followers", IsRequired = true, EmitDefaultValue = true)]
        public List<AppBskyActorDefsProfileViewBasic> Followers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AppBskyActorDefsKnownFollowers {\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  Followers: ").Append(Followers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
