/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BSky.Client.OpenAPIDateConverter;

namespace BSky.Model
{
    /// <summary>
    /// AppBskyActorDefsProfileAssociated
    /// </summary>
    [DataContract(Name = "app.bsky.actor.defs.profileAssociated")]
    public partial class AppBskyActorDefsProfileAssociated : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppBskyActorDefsProfileAssociated" /> class.
        /// </summary>
        /// <param name="lists">lists.</param>
        /// <param name="feedgens">feedgens.</param>
        /// <param name="starterPacks">starterPacks.</param>
        /// <param name="labeler">labeler.</param>
        /// <param name="chat">chat.</param>
        public AppBskyActorDefsProfileAssociated(int lists = default(int), int feedgens = default(int), int starterPacks = default(int), bool labeler = default(bool), AppBskyActorDefsProfileAssociatedChat chat = default(AppBskyActorDefsProfileAssociatedChat))
        {
            this.Lists = lists;
            this.Feedgens = feedgens;
            this.StarterPacks = starterPacks;
            this.Labeler = labeler;
            this.Chat = chat;
        }

        /// <summary>
        /// Gets or Sets Lists
        /// </summary>
        [DataMember(Name = "lists", EmitDefaultValue = false)]
        public int Lists { get; set; }

        /// <summary>
        /// Gets or Sets Feedgens
        /// </summary>
        [DataMember(Name = "feedgens", EmitDefaultValue = false)]
        public int Feedgens { get; set; }

        /// <summary>
        /// Gets or Sets StarterPacks
        /// </summary>
        [DataMember(Name = "starterPacks", EmitDefaultValue = false)]
        public int StarterPacks { get; set; }

        /// <summary>
        /// Gets or Sets Labeler
        /// </summary>
        [DataMember(Name = "labeler", EmitDefaultValue = true)]
        public bool Labeler { get; set; }

        /// <summary>
        /// Gets or Sets Chat
        /// </summary>
        [DataMember(Name = "chat", EmitDefaultValue = false)]
        public AppBskyActorDefsProfileAssociatedChat Chat { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AppBskyActorDefsProfileAssociated {\n");
            sb.Append("  Lists: ").Append(Lists).Append("\n");
            sb.Append("  Feedgens: ").Append(Feedgens).Append("\n");
            sb.Append("  StarterPacks: ").Append(StarterPacks).Append("\n");
            sb.Append("  Labeler: ").Append(Labeler).Append("\n");
            sb.Append("  Chat: ").Append(Chat).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
