/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BSky.Client.OpenAPIDateConverter;

namespace BSky.Model
{
    /// <summary>
    /// ComAtprotoServerListAppPasswords200Response
    /// </summary>
    [DataContract(Name = "com_atproto_server_listAppPasswords_200_response")]
    public partial class ComAtprotoServerListAppPasswords200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ComAtprotoServerListAppPasswords200Response" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ComAtprotoServerListAppPasswords200Response() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ComAtprotoServerListAppPasswords200Response" /> class.
        /// </summary>
        /// <param name="passwords">passwords (required).</param>
        public ComAtprotoServerListAppPasswords200Response(List<ComAtprotoServerListAppPasswordsAppPassword> passwords = default(List<ComAtprotoServerListAppPasswordsAppPassword>))
        {
            // to ensure "passwords" is required (not null)
            if (passwords == null)
            {
                throw new ArgumentNullException("passwords is a required property for ComAtprotoServerListAppPasswords200Response and cannot be null");
            }
            this.Passwords = passwords;
        }

        /// <summary>
        /// Gets or Sets Passwords
        /// </summary>
        [DataMember(Name = "passwords", IsRequired = true, EmitDefaultValue = true)]
        public List<ComAtprotoServerListAppPasswordsAppPassword> Passwords { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ComAtprotoServerListAppPasswords200Response {\n");
            sb.Append("  Passwords: ").Append(Passwords).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
