/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BSky.Client.OpenAPIDateConverter;
using System.Reflection;

namespace BSky.Model
{
    /// <summary>
    /// ComAtprotoRepoApplyWrites200ResponseResultsInner
    /// </summary>
    [JsonConverter(typeof(ComAtprotoRepoApplyWrites200ResponseResultsInnerJsonConverter))]
    [DataContract(Name = "com_atproto_repo_applyWrites_200_response_results_inner")]
    public partial class ComAtprotoRepoApplyWrites200ResponseResultsInner : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ComAtprotoRepoApplyWrites200ResponseResultsInner" /> class
        /// with the <see cref="ComAtprotoRepoApplyWritesCreateResult" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ComAtprotoRepoApplyWritesCreateResult.</param>
        public ComAtprotoRepoApplyWrites200ResponseResultsInner(ComAtprotoRepoApplyWritesCreateResult actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ComAtprotoRepoApplyWrites200ResponseResultsInner" /> class
        /// with the <see cref="ComAtprotoRepoApplyWritesUpdateResult" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ComAtprotoRepoApplyWritesUpdateResult.</param>
        public ComAtprotoRepoApplyWrites200ResponseResultsInner(ComAtprotoRepoApplyWritesUpdateResult actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ComAtprotoRepoApplyWrites200ResponseResultsInner" /> class
        /// with the <see cref="Object" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of Object.</param>
        public ComAtprotoRepoApplyWrites200ResponseResultsInner(Object actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(ComAtprotoRepoApplyWritesCreateResult) || value is ComAtprotoRepoApplyWritesCreateResult)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ComAtprotoRepoApplyWritesUpdateResult) || value is ComAtprotoRepoApplyWritesUpdateResult)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(Object) || value is Object)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: ComAtprotoRepoApplyWritesCreateResult, ComAtprotoRepoApplyWritesUpdateResult, Object");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `ComAtprotoRepoApplyWritesCreateResult`. If the actual instance is not `ComAtprotoRepoApplyWritesCreateResult`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ComAtprotoRepoApplyWritesCreateResult</returns>
        public ComAtprotoRepoApplyWritesCreateResult GetComAtprotoRepoApplyWritesCreateResult()
        {
            return (ComAtprotoRepoApplyWritesCreateResult)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ComAtprotoRepoApplyWritesUpdateResult`. If the actual instance is not `ComAtprotoRepoApplyWritesUpdateResult`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ComAtprotoRepoApplyWritesUpdateResult</returns>
        public ComAtprotoRepoApplyWritesUpdateResult GetComAtprotoRepoApplyWritesUpdateResult()
        {
            return (ComAtprotoRepoApplyWritesUpdateResult)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `Object`. If the actual instance is not `Object`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of Object</returns>
        public Object GetObject()
        {
            return (Object)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ComAtprotoRepoApplyWrites200ResponseResultsInner {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, ComAtprotoRepoApplyWrites200ResponseResultsInner.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of ComAtprotoRepoApplyWrites200ResponseResultsInner
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of ComAtprotoRepoApplyWrites200ResponseResultsInner</returns>
        public static ComAtprotoRepoApplyWrites200ResponseResultsInner FromJson(string jsonString)
        {
            ComAtprotoRepoApplyWrites200ResponseResultsInner newComAtprotoRepoApplyWrites200ResponseResultsInner = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newComAtprotoRepoApplyWrites200ResponseResultsInner;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ComAtprotoRepoApplyWritesCreateResult).GetProperty("AdditionalProperties") == null)
                {
                    newComAtprotoRepoApplyWrites200ResponseResultsInner = new ComAtprotoRepoApplyWrites200ResponseResultsInner(JsonConvert.DeserializeObject<ComAtprotoRepoApplyWritesCreateResult>(jsonString, ComAtprotoRepoApplyWrites200ResponseResultsInner.SerializerSettings));
                }
                else
                {
                    newComAtprotoRepoApplyWrites200ResponseResultsInner = new ComAtprotoRepoApplyWrites200ResponseResultsInner(JsonConvert.DeserializeObject<ComAtprotoRepoApplyWritesCreateResult>(jsonString, ComAtprotoRepoApplyWrites200ResponseResultsInner.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ComAtprotoRepoApplyWritesCreateResult");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ComAtprotoRepoApplyWritesCreateResult: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ComAtprotoRepoApplyWritesUpdateResult).GetProperty("AdditionalProperties") == null)
                {
                    newComAtprotoRepoApplyWrites200ResponseResultsInner = new ComAtprotoRepoApplyWrites200ResponseResultsInner(JsonConvert.DeserializeObject<ComAtprotoRepoApplyWritesUpdateResult>(jsonString, ComAtprotoRepoApplyWrites200ResponseResultsInner.SerializerSettings));
                }
                else
                {
                    newComAtprotoRepoApplyWrites200ResponseResultsInner = new ComAtprotoRepoApplyWrites200ResponseResultsInner(JsonConvert.DeserializeObject<ComAtprotoRepoApplyWritesUpdateResult>(jsonString, ComAtprotoRepoApplyWrites200ResponseResultsInner.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ComAtprotoRepoApplyWritesUpdateResult");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ComAtprotoRepoApplyWritesUpdateResult: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(Object).GetProperty("AdditionalProperties") == null)
                {
                    newComAtprotoRepoApplyWrites200ResponseResultsInner = new ComAtprotoRepoApplyWrites200ResponseResultsInner(JsonConvert.DeserializeObject<Object>(jsonString, ComAtprotoRepoApplyWrites200ResponseResultsInner.SerializerSettings));
                }
                else
                {
                    newComAtprotoRepoApplyWrites200ResponseResultsInner = new ComAtprotoRepoApplyWrites200ResponseResultsInner(JsonConvert.DeserializeObject<Object>(jsonString, ComAtprotoRepoApplyWrites200ResponseResultsInner.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("Object");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into Object: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newComAtprotoRepoApplyWrites200ResponseResultsInner;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for ComAtprotoRepoApplyWrites200ResponseResultsInner
    /// </summary>
    public class ComAtprotoRepoApplyWrites200ResponseResultsInnerJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(ComAtprotoRepoApplyWrites200ResponseResultsInner).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return ComAtprotoRepoApplyWrites200ResponseResultsInner.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return ComAtprotoRepoApplyWrites200ResponseResultsInner.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
