/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BSky.Client.OpenAPIDateConverter;

namespace BSky.Model
{
    /// <summary>
    /// ComAtprotoModerationCreateReport200Response
    /// </summary>
    [DataContract(Name = "com_atproto_moderation_createReport_200_response")]
    public partial class ComAtprotoModerationCreateReport200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ComAtprotoModerationCreateReport200Response" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ComAtprotoModerationCreateReport200Response() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ComAtprotoModerationCreateReport200Response" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="reasonType">reasonType (required).</param>
        /// <param name="reason">reason.</param>
        /// <param name="subject">subject (required).</param>
        /// <param name="reportedBy">reportedBy (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        public ComAtprotoModerationCreateReport200Response(int id = default(int), ComAtprotoModerationDefsReasonType reasonType = default(ComAtprotoModerationDefsReasonType), string reason = default(string), ComAtprotoModerationCreateReportRequestSubject subject = default(ComAtprotoModerationCreateReportRequestSubject), string reportedBy = default(string), DateTime createdAt = default(DateTime))
        {
            this.Id = id;
            // to ensure "reasonType" is required (not null)
            if (reasonType == null)
            {
                throw new ArgumentNullException("reasonType is a required property for ComAtprotoModerationCreateReport200Response and cannot be null");
            }
            this.ReasonType = reasonType;
            // to ensure "subject" is required (not null)
            if (subject == null)
            {
                throw new ArgumentNullException("subject is a required property for ComAtprotoModerationCreateReport200Response and cannot be null");
            }
            this.Subject = subject;
            // to ensure "reportedBy" is required (not null)
            if (reportedBy == null)
            {
                throw new ArgumentNullException("reportedBy is a required property for ComAtprotoModerationCreateReport200Response and cannot be null");
            }
            this.ReportedBy = reportedBy;
            this.CreatedAt = createdAt;
            this.Reason = reason;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets ReasonType
        /// </summary>
        [DataMember(Name = "reasonType", IsRequired = true, EmitDefaultValue = true)]
        public ComAtprotoModerationDefsReasonType ReasonType { get; set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [DataMember(Name = "reason", EmitDefaultValue = false)]
        public string Reason { get; set; }

        /// <summary>
        /// Gets or Sets Subject
        /// </summary>
        [DataMember(Name = "subject", IsRequired = true, EmitDefaultValue = true)]
        public ComAtprotoModerationCreateReportRequestSubject Subject { get; set; }

        /// <summary>
        /// Gets or Sets ReportedBy
        /// </summary>
        [DataMember(Name = "reportedBy", IsRequired = true, EmitDefaultValue = true)]
        public string ReportedBy { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ComAtprotoModerationCreateReport200Response {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ReasonType: ").Append(ReasonType).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  ReportedBy: ").Append(ReportedBy).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Reason (string) maxLength
            if (this.Reason != null && this.Reason.Length > 20000)
            {
                yield return new ValidationResult("Invalid value for Reason, length must be less than 20000.", new [] { "Reason" });
            }

            yield break;
        }
    }

}
