/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BSky.Client.OpenAPIDateConverter;

namespace BSky.Model
{
    /// <summary>
    /// ComAtprotoAdminUpdateSubjectStatus200Response
    /// </summary>
    [DataContract(Name = "com_atproto_admin_updateSubjectStatus_200_response")]
    public partial class ComAtprotoAdminUpdateSubjectStatus200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ComAtprotoAdminUpdateSubjectStatus200Response" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ComAtprotoAdminUpdateSubjectStatus200Response() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ComAtprotoAdminUpdateSubjectStatus200Response" /> class.
        /// </summary>
        /// <param name="subject">subject (required).</param>
        /// <param name="takedown">takedown.</param>
        public ComAtprotoAdminUpdateSubjectStatus200Response(ComAtprotoAdminGetSubjectStatus200ResponseSubject subject = default(ComAtprotoAdminGetSubjectStatus200ResponseSubject), ComAtprotoAdminDefsStatusAttr takedown = default(ComAtprotoAdminDefsStatusAttr))
        {
            // to ensure "subject" is required (not null)
            if (subject == null)
            {
                throw new ArgumentNullException("subject is a required property for ComAtprotoAdminUpdateSubjectStatus200Response and cannot be null");
            }
            this.Subject = subject;
            this.Takedown = takedown;
        }

        /// <summary>
        /// Gets or Sets Subject
        /// </summary>
        [DataMember(Name = "subject", IsRequired = true, EmitDefaultValue = true)]
        public ComAtprotoAdminGetSubjectStatus200ResponseSubject Subject { get; set; }

        /// <summary>
        /// Gets or Sets Takedown
        /// </summary>
        [DataMember(Name = "takedown", EmitDefaultValue = false)]
        public ComAtprotoAdminDefsStatusAttr Takedown { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ComAtprotoAdminUpdateSubjectStatus200Response {\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  Takedown: ").Append(Takedown).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
