/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BSky.Client.OpenAPIDateConverter;

namespace BSky.Model
{
    /// <summary>
    /// ToolsOzoneModerationEmitEventRequest
    /// </summary>
    [DataContract(Name = "tools_ozone_moderation_emitEvent_request")]
    public partial class ToolsOzoneModerationEmitEventRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsOzoneModerationEmitEventRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ToolsOzoneModerationEmitEventRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsOzoneModerationEmitEventRequest" /> class.
        /// </summary>
        /// <param name="varEvent">varEvent (required).</param>
        /// <param name="subject">subject (required).</param>
        /// <param name="subjectBlobCids">subjectBlobCids.</param>
        /// <param name="createdBy">createdBy (required).</param>
        public ToolsOzoneModerationEmitEventRequest(ToolsOzoneModerationEmitEventRequestEvent varEvent = default(ToolsOzoneModerationEmitEventRequestEvent), ComAtprotoModerationCreateReportRequestSubject subject = default(ComAtprotoModerationCreateReportRequestSubject), List<string> subjectBlobCids = default(List<string>), string createdBy = default(string))
        {
            // to ensure "varEvent" is required (not null)
            if (varEvent == null)
            {
                throw new ArgumentNullException("varEvent is a required property for ToolsOzoneModerationEmitEventRequest and cannot be null");
            }
            this.Event = varEvent;
            // to ensure "subject" is required (not null)
            if (subject == null)
            {
                throw new ArgumentNullException("subject is a required property for ToolsOzoneModerationEmitEventRequest and cannot be null");
            }
            this.Subject = subject;
            // to ensure "createdBy" is required (not null)
            if (createdBy == null)
            {
                throw new ArgumentNullException("createdBy is a required property for ToolsOzoneModerationEmitEventRequest and cannot be null");
            }
            this.CreatedBy = createdBy;
            this.SubjectBlobCids = subjectBlobCids;
        }

        /// <summary>
        /// Gets or Sets Event
        /// </summary>
        [DataMember(Name = "event", IsRequired = true, EmitDefaultValue = true)]
        public ToolsOzoneModerationEmitEventRequestEvent Event { get; set; }

        /// <summary>
        /// Gets or Sets Subject
        /// </summary>
        [DataMember(Name = "subject", IsRequired = true, EmitDefaultValue = true)]
        public ComAtprotoModerationCreateReportRequestSubject Subject { get; set; }

        /// <summary>
        /// Gets or Sets SubjectBlobCids
        /// </summary>
        [DataMember(Name = "subjectBlobCids", EmitDefaultValue = false)]
        public List<string> SubjectBlobCids { get; set; }

        /// <summary>
        /// Gets or Sets CreatedBy
        /// </summary>
        [DataMember(Name = "createdBy", IsRequired = true, EmitDefaultValue = true)]
        public string CreatedBy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ToolsOzoneModerationEmitEventRequest {\n");
            sb.Append("  Event: ").Append(Event).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  SubjectBlobCids: ").Append(SubjectBlobCids).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
