/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BSky.Client.OpenAPIDateConverter;
using System.Reflection;

namespace BSky.Model
{
    /// <summary>
    /// ToolsOzoneModerationEmitEventRequestEvent
    /// </summary>
    [JsonConverter(typeof(ToolsOzoneModerationEmitEventRequestEventJsonConverter))]
    [DataContract(Name = "tools_ozone_moderation_emitEvent_request_event")]
    public partial class ToolsOzoneModerationEmitEventRequestEvent : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsOzoneModerationEmitEventRequestEvent" /> class
        /// with the <see cref="ToolsOzoneModerationDefsModEventTakedown" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ToolsOzoneModerationDefsModEventTakedown.</param>
        public ToolsOzoneModerationEmitEventRequestEvent(ToolsOzoneModerationDefsModEventTakedown actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsOzoneModerationEmitEventRequestEvent" /> class
        /// with the <see cref="ToolsOzoneModerationDefsModEventAcknowledge" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ToolsOzoneModerationDefsModEventAcknowledge.</param>
        public ToolsOzoneModerationEmitEventRequestEvent(ToolsOzoneModerationDefsModEventAcknowledge actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsOzoneModerationEmitEventRequestEvent" /> class
        /// with the <see cref="ToolsOzoneModerationDefsModEventEscalate" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ToolsOzoneModerationDefsModEventEscalate.</param>
        public ToolsOzoneModerationEmitEventRequestEvent(ToolsOzoneModerationDefsModEventEscalate actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsOzoneModerationEmitEventRequestEvent" /> class
        /// with the <see cref="ToolsOzoneModerationDefsModEventComment" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ToolsOzoneModerationDefsModEventComment.</param>
        public ToolsOzoneModerationEmitEventRequestEvent(ToolsOzoneModerationDefsModEventComment actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsOzoneModerationEmitEventRequestEvent" /> class
        /// with the <see cref="ToolsOzoneModerationDefsModEventLabel" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ToolsOzoneModerationDefsModEventLabel.</param>
        public ToolsOzoneModerationEmitEventRequestEvent(ToolsOzoneModerationDefsModEventLabel actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsOzoneModerationEmitEventRequestEvent" /> class
        /// with the <see cref="ToolsOzoneModerationDefsModEventReport" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ToolsOzoneModerationDefsModEventReport.</param>
        public ToolsOzoneModerationEmitEventRequestEvent(ToolsOzoneModerationDefsModEventReport actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsOzoneModerationEmitEventRequestEvent" /> class
        /// with the <see cref="ToolsOzoneModerationDefsModEventMute" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ToolsOzoneModerationDefsModEventMute.</param>
        public ToolsOzoneModerationEmitEventRequestEvent(ToolsOzoneModerationDefsModEventMute actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsOzoneModerationEmitEventRequestEvent" /> class
        /// with the <see cref="ToolsOzoneModerationDefsModEventUnmute" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ToolsOzoneModerationDefsModEventUnmute.</param>
        public ToolsOzoneModerationEmitEventRequestEvent(ToolsOzoneModerationDefsModEventUnmute actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsOzoneModerationEmitEventRequestEvent" /> class
        /// with the <see cref="ToolsOzoneModerationDefsModEventMuteReporter" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ToolsOzoneModerationDefsModEventMuteReporter.</param>
        public ToolsOzoneModerationEmitEventRequestEvent(ToolsOzoneModerationDefsModEventMuteReporter actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsOzoneModerationEmitEventRequestEvent" /> class
        /// with the <see cref="ToolsOzoneModerationDefsModEventUnmuteReporter" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ToolsOzoneModerationDefsModEventUnmuteReporter.</param>
        public ToolsOzoneModerationEmitEventRequestEvent(ToolsOzoneModerationDefsModEventUnmuteReporter actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsOzoneModerationEmitEventRequestEvent" /> class
        /// with the <see cref="ToolsOzoneModerationDefsModEventReverseTakedown" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ToolsOzoneModerationDefsModEventReverseTakedown.</param>
        public ToolsOzoneModerationEmitEventRequestEvent(ToolsOzoneModerationDefsModEventReverseTakedown actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsOzoneModerationEmitEventRequestEvent" /> class
        /// with the <see cref="ToolsOzoneModerationDefsModEventResolveAppeal" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ToolsOzoneModerationDefsModEventResolveAppeal.</param>
        public ToolsOzoneModerationEmitEventRequestEvent(ToolsOzoneModerationDefsModEventResolveAppeal actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsOzoneModerationEmitEventRequestEvent" /> class
        /// with the <see cref="ToolsOzoneModerationDefsModEventEmail" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ToolsOzoneModerationDefsModEventEmail.</param>
        public ToolsOzoneModerationEmitEventRequestEvent(ToolsOzoneModerationDefsModEventEmail actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsOzoneModerationEmitEventRequestEvent" /> class
        /// with the <see cref="ToolsOzoneModerationDefsModEventTag" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ToolsOzoneModerationDefsModEventTag.</param>
        public ToolsOzoneModerationEmitEventRequestEvent(ToolsOzoneModerationDefsModEventTag actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(ToolsOzoneModerationDefsModEventAcknowledge) || value is ToolsOzoneModerationDefsModEventAcknowledge)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ToolsOzoneModerationDefsModEventComment) || value is ToolsOzoneModerationDefsModEventComment)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ToolsOzoneModerationDefsModEventEmail) || value is ToolsOzoneModerationDefsModEventEmail)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ToolsOzoneModerationDefsModEventEscalate) || value is ToolsOzoneModerationDefsModEventEscalate)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ToolsOzoneModerationDefsModEventLabel) || value is ToolsOzoneModerationDefsModEventLabel)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ToolsOzoneModerationDefsModEventMute) || value is ToolsOzoneModerationDefsModEventMute)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ToolsOzoneModerationDefsModEventMuteReporter) || value is ToolsOzoneModerationDefsModEventMuteReporter)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ToolsOzoneModerationDefsModEventReport) || value is ToolsOzoneModerationDefsModEventReport)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ToolsOzoneModerationDefsModEventResolveAppeal) || value is ToolsOzoneModerationDefsModEventResolveAppeal)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ToolsOzoneModerationDefsModEventReverseTakedown) || value is ToolsOzoneModerationDefsModEventReverseTakedown)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ToolsOzoneModerationDefsModEventTag) || value is ToolsOzoneModerationDefsModEventTag)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ToolsOzoneModerationDefsModEventTakedown) || value is ToolsOzoneModerationDefsModEventTakedown)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ToolsOzoneModerationDefsModEventUnmute) || value is ToolsOzoneModerationDefsModEventUnmute)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ToolsOzoneModerationDefsModEventUnmuteReporter) || value is ToolsOzoneModerationDefsModEventUnmuteReporter)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: ToolsOzoneModerationDefsModEventAcknowledge, ToolsOzoneModerationDefsModEventComment, ToolsOzoneModerationDefsModEventEmail, ToolsOzoneModerationDefsModEventEscalate, ToolsOzoneModerationDefsModEventLabel, ToolsOzoneModerationDefsModEventMute, ToolsOzoneModerationDefsModEventMuteReporter, ToolsOzoneModerationDefsModEventReport, ToolsOzoneModerationDefsModEventResolveAppeal, ToolsOzoneModerationDefsModEventReverseTakedown, ToolsOzoneModerationDefsModEventTag, ToolsOzoneModerationDefsModEventTakedown, ToolsOzoneModerationDefsModEventUnmute, ToolsOzoneModerationDefsModEventUnmuteReporter");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `ToolsOzoneModerationDefsModEventTakedown`. If the actual instance is not `ToolsOzoneModerationDefsModEventTakedown`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ToolsOzoneModerationDefsModEventTakedown</returns>
        public ToolsOzoneModerationDefsModEventTakedown GetToolsOzoneModerationDefsModEventTakedown()
        {
            return (ToolsOzoneModerationDefsModEventTakedown)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ToolsOzoneModerationDefsModEventAcknowledge`. If the actual instance is not `ToolsOzoneModerationDefsModEventAcknowledge`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ToolsOzoneModerationDefsModEventAcknowledge</returns>
        public ToolsOzoneModerationDefsModEventAcknowledge GetToolsOzoneModerationDefsModEventAcknowledge()
        {
            return (ToolsOzoneModerationDefsModEventAcknowledge)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ToolsOzoneModerationDefsModEventEscalate`. If the actual instance is not `ToolsOzoneModerationDefsModEventEscalate`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ToolsOzoneModerationDefsModEventEscalate</returns>
        public ToolsOzoneModerationDefsModEventEscalate GetToolsOzoneModerationDefsModEventEscalate()
        {
            return (ToolsOzoneModerationDefsModEventEscalate)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ToolsOzoneModerationDefsModEventComment`. If the actual instance is not `ToolsOzoneModerationDefsModEventComment`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ToolsOzoneModerationDefsModEventComment</returns>
        public ToolsOzoneModerationDefsModEventComment GetToolsOzoneModerationDefsModEventComment()
        {
            return (ToolsOzoneModerationDefsModEventComment)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ToolsOzoneModerationDefsModEventLabel`. If the actual instance is not `ToolsOzoneModerationDefsModEventLabel`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ToolsOzoneModerationDefsModEventLabel</returns>
        public ToolsOzoneModerationDefsModEventLabel GetToolsOzoneModerationDefsModEventLabel()
        {
            return (ToolsOzoneModerationDefsModEventLabel)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ToolsOzoneModerationDefsModEventReport`. If the actual instance is not `ToolsOzoneModerationDefsModEventReport`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ToolsOzoneModerationDefsModEventReport</returns>
        public ToolsOzoneModerationDefsModEventReport GetToolsOzoneModerationDefsModEventReport()
        {
            return (ToolsOzoneModerationDefsModEventReport)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ToolsOzoneModerationDefsModEventMute`. If the actual instance is not `ToolsOzoneModerationDefsModEventMute`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ToolsOzoneModerationDefsModEventMute</returns>
        public ToolsOzoneModerationDefsModEventMute GetToolsOzoneModerationDefsModEventMute()
        {
            return (ToolsOzoneModerationDefsModEventMute)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ToolsOzoneModerationDefsModEventUnmute`. If the actual instance is not `ToolsOzoneModerationDefsModEventUnmute`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ToolsOzoneModerationDefsModEventUnmute</returns>
        public ToolsOzoneModerationDefsModEventUnmute GetToolsOzoneModerationDefsModEventUnmute()
        {
            return (ToolsOzoneModerationDefsModEventUnmute)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ToolsOzoneModerationDefsModEventMuteReporter`. If the actual instance is not `ToolsOzoneModerationDefsModEventMuteReporter`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ToolsOzoneModerationDefsModEventMuteReporter</returns>
        public ToolsOzoneModerationDefsModEventMuteReporter GetToolsOzoneModerationDefsModEventMuteReporter()
        {
            return (ToolsOzoneModerationDefsModEventMuteReporter)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ToolsOzoneModerationDefsModEventUnmuteReporter`. If the actual instance is not `ToolsOzoneModerationDefsModEventUnmuteReporter`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ToolsOzoneModerationDefsModEventUnmuteReporter</returns>
        public ToolsOzoneModerationDefsModEventUnmuteReporter GetToolsOzoneModerationDefsModEventUnmuteReporter()
        {
            return (ToolsOzoneModerationDefsModEventUnmuteReporter)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ToolsOzoneModerationDefsModEventReverseTakedown`. If the actual instance is not `ToolsOzoneModerationDefsModEventReverseTakedown`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ToolsOzoneModerationDefsModEventReverseTakedown</returns>
        public ToolsOzoneModerationDefsModEventReverseTakedown GetToolsOzoneModerationDefsModEventReverseTakedown()
        {
            return (ToolsOzoneModerationDefsModEventReverseTakedown)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ToolsOzoneModerationDefsModEventResolveAppeal`. If the actual instance is not `ToolsOzoneModerationDefsModEventResolveAppeal`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ToolsOzoneModerationDefsModEventResolveAppeal</returns>
        public ToolsOzoneModerationDefsModEventResolveAppeal GetToolsOzoneModerationDefsModEventResolveAppeal()
        {
            return (ToolsOzoneModerationDefsModEventResolveAppeal)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ToolsOzoneModerationDefsModEventEmail`. If the actual instance is not `ToolsOzoneModerationDefsModEventEmail`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ToolsOzoneModerationDefsModEventEmail</returns>
        public ToolsOzoneModerationDefsModEventEmail GetToolsOzoneModerationDefsModEventEmail()
        {
            return (ToolsOzoneModerationDefsModEventEmail)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ToolsOzoneModerationDefsModEventTag`. If the actual instance is not `ToolsOzoneModerationDefsModEventTag`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ToolsOzoneModerationDefsModEventTag</returns>
        public ToolsOzoneModerationDefsModEventTag GetToolsOzoneModerationDefsModEventTag()
        {
            return (ToolsOzoneModerationDefsModEventTag)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ToolsOzoneModerationEmitEventRequestEvent {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, ToolsOzoneModerationEmitEventRequestEvent.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of ToolsOzoneModerationEmitEventRequestEvent
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of ToolsOzoneModerationEmitEventRequestEvent</returns>
        public static ToolsOzoneModerationEmitEventRequestEvent FromJson(string jsonString)
        {
            ToolsOzoneModerationEmitEventRequestEvent newToolsOzoneModerationEmitEventRequestEvent = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newToolsOzoneModerationEmitEventRequestEvent;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ToolsOzoneModerationDefsModEventAcknowledge).GetProperty("AdditionalProperties") == null)
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventAcknowledge>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.SerializerSettings));
                }
                else
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventAcknowledge>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ToolsOzoneModerationDefsModEventAcknowledge");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ToolsOzoneModerationDefsModEventAcknowledge: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ToolsOzoneModerationDefsModEventComment).GetProperty("AdditionalProperties") == null)
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventComment>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.SerializerSettings));
                }
                else
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventComment>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ToolsOzoneModerationDefsModEventComment");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ToolsOzoneModerationDefsModEventComment: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ToolsOzoneModerationDefsModEventEmail).GetProperty("AdditionalProperties") == null)
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventEmail>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.SerializerSettings));
                }
                else
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventEmail>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ToolsOzoneModerationDefsModEventEmail");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ToolsOzoneModerationDefsModEventEmail: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ToolsOzoneModerationDefsModEventEscalate).GetProperty("AdditionalProperties") == null)
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventEscalate>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.SerializerSettings));
                }
                else
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventEscalate>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ToolsOzoneModerationDefsModEventEscalate");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ToolsOzoneModerationDefsModEventEscalate: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ToolsOzoneModerationDefsModEventLabel).GetProperty("AdditionalProperties") == null)
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventLabel>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.SerializerSettings));
                }
                else
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventLabel>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ToolsOzoneModerationDefsModEventLabel");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ToolsOzoneModerationDefsModEventLabel: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ToolsOzoneModerationDefsModEventMute).GetProperty("AdditionalProperties") == null)
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventMute>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.SerializerSettings));
                }
                else
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventMute>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ToolsOzoneModerationDefsModEventMute");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ToolsOzoneModerationDefsModEventMute: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ToolsOzoneModerationDefsModEventMuteReporter).GetProperty("AdditionalProperties") == null)
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventMuteReporter>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.SerializerSettings));
                }
                else
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventMuteReporter>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ToolsOzoneModerationDefsModEventMuteReporter");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ToolsOzoneModerationDefsModEventMuteReporter: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ToolsOzoneModerationDefsModEventReport).GetProperty("AdditionalProperties") == null)
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventReport>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.SerializerSettings));
                }
                else
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventReport>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ToolsOzoneModerationDefsModEventReport");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ToolsOzoneModerationDefsModEventReport: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ToolsOzoneModerationDefsModEventResolveAppeal).GetProperty("AdditionalProperties") == null)
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventResolveAppeal>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.SerializerSettings));
                }
                else
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventResolveAppeal>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ToolsOzoneModerationDefsModEventResolveAppeal");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ToolsOzoneModerationDefsModEventResolveAppeal: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ToolsOzoneModerationDefsModEventReverseTakedown).GetProperty("AdditionalProperties") == null)
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventReverseTakedown>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.SerializerSettings));
                }
                else
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventReverseTakedown>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ToolsOzoneModerationDefsModEventReverseTakedown");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ToolsOzoneModerationDefsModEventReverseTakedown: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ToolsOzoneModerationDefsModEventTag).GetProperty("AdditionalProperties") == null)
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventTag>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.SerializerSettings));
                }
                else
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventTag>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ToolsOzoneModerationDefsModEventTag");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ToolsOzoneModerationDefsModEventTag: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ToolsOzoneModerationDefsModEventTakedown).GetProperty("AdditionalProperties") == null)
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventTakedown>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.SerializerSettings));
                }
                else
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventTakedown>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ToolsOzoneModerationDefsModEventTakedown");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ToolsOzoneModerationDefsModEventTakedown: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ToolsOzoneModerationDefsModEventUnmute).GetProperty("AdditionalProperties") == null)
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventUnmute>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.SerializerSettings));
                }
                else
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventUnmute>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ToolsOzoneModerationDefsModEventUnmute");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ToolsOzoneModerationDefsModEventUnmute: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ToolsOzoneModerationDefsModEventUnmuteReporter).GetProperty("AdditionalProperties") == null)
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventUnmuteReporter>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.SerializerSettings));
                }
                else
                {
                    newToolsOzoneModerationEmitEventRequestEvent = new ToolsOzoneModerationEmitEventRequestEvent(JsonConvert.DeserializeObject<ToolsOzoneModerationDefsModEventUnmuteReporter>(jsonString, ToolsOzoneModerationEmitEventRequestEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ToolsOzoneModerationDefsModEventUnmuteReporter");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ToolsOzoneModerationDefsModEventUnmuteReporter: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newToolsOzoneModerationEmitEventRequestEvent;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for ToolsOzoneModerationEmitEventRequestEvent
    /// </summary>
    public class ToolsOzoneModerationEmitEventRequestEventJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(ToolsOzoneModerationEmitEventRequestEvent).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return ToolsOzoneModerationEmitEventRequestEvent.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return ToolsOzoneModerationEmitEventRequestEvent.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
