/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BSky.Client.OpenAPIDateConverter;

namespace BSky.Model
{
    /// <summary>
    /// ToolsOzoneServerGetConfigViewerConfig
    /// </summary>
    [DataContract(Name = "tools.ozone.server.getConfig.viewerConfig")]
    public partial class ToolsOzoneServerGetConfigViewerConfig : IValidatableObject
    {
        /// <summary>
        /// Defines Role
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RoleEnum
        {
            /// <summary>
            /// Enum RoleAdmin for value: tools.ozone.team.defs#roleAdmin
            /// </summary>
            [EnumMember(Value = "tools.ozone.team.defs#roleAdmin")]
            RoleAdmin = 1,

            /// <summary>
            /// Enum RoleModerator for value: tools.ozone.team.defs#roleModerator
            /// </summary>
            [EnumMember(Value = "tools.ozone.team.defs#roleModerator")]
            RoleModerator = 2,

            /// <summary>
            /// Enum RoleTriage for value: tools.ozone.team.defs#roleTriage
            /// </summary>
            [EnumMember(Value = "tools.ozone.team.defs#roleTriage")]
            RoleTriage = 3
        }


        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [DataMember(Name = "role", EmitDefaultValue = false)]
        public RoleEnum? Role { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsOzoneServerGetConfigViewerConfig" /> class.
        /// </summary>
        /// <param name="role">role.</param>
        public ToolsOzoneServerGetConfigViewerConfig(RoleEnum? role = default(RoleEnum?))
        {
            this.Role = role;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ToolsOzoneServerGetConfigViewerConfig {\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
