/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyRichtextFacetFeaturesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyRichtextFacetFeaturesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyRichtextFacetFeaturesInner
        //private AppBskyRichtextFacetFeaturesInner instance;

        public AppBskyRichtextFacetFeaturesInnerTests()
        {
            // TODO uncomment below to create an instance of AppBskyRichtextFacetFeaturesInner
            //instance = new AppBskyRichtextFacetFeaturesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyRichtextFacetFeaturesInner
        /// </summary>
        [Fact]
        public void AppBskyRichtextFacetFeaturesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyRichtextFacetFeaturesInner
            //Assert.IsType<AppBskyRichtextFacetFeaturesInner>(instance);
        }

        /// <summary>
        /// Test the property 'Did'
        /// </summary>
        [Fact]
        public void DidTest()
        {
            // TODO unit test for the property 'Did'
        }

        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }

        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Fact]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }
    }
}
