/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyEmbedRecordWithMediaMedia
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyEmbedRecordWithMediaMediaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyEmbedRecordWithMediaMedia
        //private AppBskyEmbedRecordWithMediaMedia instance;

        public AppBskyEmbedRecordWithMediaMediaTests()
        {
            // TODO uncomment below to create an instance of AppBskyEmbedRecordWithMediaMedia
            //instance = new AppBskyEmbedRecordWithMediaMedia();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyEmbedRecordWithMediaMedia
        /// </summary>
        [Fact]
        public void AppBskyEmbedRecordWithMediaMediaInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyEmbedRecordWithMediaMedia
            //Assert.IsType<AppBskyEmbedRecordWithMediaMedia>(instance);
        }

        /// <summary>
        /// Test the property 'Images'
        /// </summary>
        [Fact]
        public void ImagesTest()
        {
            // TODO unit test for the property 'Images'
        }

        /// <summary>
        /// Test the property 'Video'
        /// </summary>
        [Fact]
        public void VideoTest()
        {
            // TODO unit test for the property 'Video'
        }

        /// <summary>
        /// Test the property 'Captions'
        /// </summary>
        [Fact]
        public void CaptionsTest()
        {
            // TODO unit test for the property 'Captions'
        }

        /// <summary>
        /// Test the property 'Alt'
        /// </summary>
        [Fact]
        public void AltTest()
        {
            // TODO unit test for the property 'Alt'
        }

        /// <summary>
        /// Test the property 'AspectRatio'
        /// </summary>
        [Fact]
        public void AspectRatioTest()
        {
            // TODO unit test for the property 'AspectRatio'
        }

        /// <summary>
        /// Test the property 'External'
        /// </summary>
        [Fact]
        public void ExternalTest()
        {
            // TODO unit test for the property 'External'
        }
    }
}
