/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyGraphStarterpackFeedItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyGraphStarterpackFeedItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyGraphStarterpackFeedItem
        //private AppBskyGraphStarterpackFeedItem instance;

        public AppBskyGraphStarterpackFeedItemTests()
        {
            // TODO uncomment below to create an instance of AppBskyGraphStarterpackFeedItem
            //instance = new AppBskyGraphStarterpackFeedItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyGraphStarterpackFeedItem
        /// </summary>
        [Fact]
        public void AppBskyGraphStarterpackFeedItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyGraphStarterpackFeedItem
            //Assert.IsType<AppBskyGraphStarterpackFeedItem>(instance);
        }

        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
    }
}
