/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyFeedDefsPostView
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyFeedDefsPostViewTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyFeedDefsPostView
        //private AppBskyFeedDefsPostView instance;

        public AppBskyFeedDefsPostViewTests()
        {
            // TODO uncomment below to create an instance of AppBskyFeedDefsPostView
            //instance = new AppBskyFeedDefsPostView();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyFeedDefsPostView
        /// </summary>
        [Fact]
        public void AppBskyFeedDefsPostViewInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyFeedDefsPostView
            //Assert.IsType<AppBskyFeedDefsPostView>(instance);
        }

        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }

        /// <summary>
        /// Test the property 'Cid'
        /// </summary>
        [Fact]
        public void CidTest()
        {
            // TODO unit test for the property 'Cid'
        }

        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Fact]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }

        /// <summary>
        /// Test the property 'Record'
        /// </summary>
        [Fact]
        public void RecordTest()
        {
            // TODO unit test for the property 'Record'
        }

        /// <summary>
        /// Test the property 'Embed'
        /// </summary>
        [Fact]
        public void EmbedTest()
        {
            // TODO unit test for the property 'Embed'
        }

        /// <summary>
        /// Test the property 'ReplyCount'
        /// </summary>
        [Fact]
        public void ReplyCountTest()
        {
            // TODO unit test for the property 'ReplyCount'
        }

        /// <summary>
        /// Test the property 'RepostCount'
        /// </summary>
        [Fact]
        public void RepostCountTest()
        {
            // TODO unit test for the property 'RepostCount'
        }

        /// <summary>
        /// Test the property 'LikeCount'
        /// </summary>
        [Fact]
        public void LikeCountTest()
        {
            // TODO unit test for the property 'LikeCount'
        }

        /// <summary>
        /// Test the property 'QuoteCount'
        /// </summary>
        [Fact]
        public void QuoteCountTest()
        {
            // TODO unit test for the property 'QuoteCount'
        }

        /// <summary>
        /// Test the property 'IndexedAt'
        /// </summary>
        [Fact]
        public void IndexedAtTest()
        {
            // TODO unit test for the property 'IndexedAt'
        }

        /// <summary>
        /// Test the property 'Viewer'
        /// </summary>
        [Fact]
        public void ViewerTest()
        {
            // TODO unit test for the property 'Viewer'
        }

        /// <summary>
        /// Test the property 'Labels'
        /// </summary>
        [Fact]
        public void LabelsTest()
        {
            // TODO unit test for the property 'Labels'
        }

        /// <summary>
        /// Test the property 'Threadgate'
        /// </summary>
        [Fact]
        public void ThreadgateTest()
        {
            // TODO unit test for the property 'Threadgate'
        }
    }
}
