/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyGraphGetRelationships200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyGraphGetRelationships200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyGraphGetRelationships200Response
        //private AppBskyGraphGetRelationships200Response instance;

        public AppBskyGraphGetRelationships200ResponseTests()
        {
            // TODO uncomment below to create an instance of AppBskyGraphGetRelationships200Response
            //instance = new AppBskyGraphGetRelationships200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyGraphGetRelationships200Response
        /// </summary>
        [Fact]
        public void AppBskyGraphGetRelationships200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyGraphGetRelationships200Response
            //Assert.IsType<AppBskyGraphGetRelationships200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Actor'
        /// </summary>
        [Fact]
        public void ActorTest()
        {
            // TODO unit test for the property 'Actor'
        }

        /// <summary>
        /// Test the property 'Relationships'
        /// </summary>
        [Fact]
        public void RelationshipsTest()
        {
            // TODO unit test for the property 'Relationships'
        }
    }
}
