/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyActorDefsContentLabelPref
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyActorDefsContentLabelPrefTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyActorDefsContentLabelPref
        //private AppBskyActorDefsContentLabelPref instance;

        public AppBskyActorDefsContentLabelPrefTests()
        {
            // TODO uncomment below to create an instance of AppBskyActorDefsContentLabelPref
            //instance = new AppBskyActorDefsContentLabelPref();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyActorDefsContentLabelPref
        /// </summary>
        [Fact]
        public void AppBskyActorDefsContentLabelPrefInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyActorDefsContentLabelPref
            //Assert.IsType<AppBskyActorDefsContentLabelPref>(instance);
        }

        /// <summary>
        /// Test the property 'LabelerDid'
        /// </summary>
        [Fact]
        public void LabelerDidTest()
        {
            // TODO unit test for the property 'LabelerDid'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'Visibility'
        /// </summary>
        [Fact]
        public void VisibilityTest()
        {
            // TODO unit test for the property 'Visibility'
        }
    }
}
