/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyGraphDefsListView
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyGraphDefsListViewTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyGraphDefsListView
        //private AppBskyGraphDefsListView instance;

        public AppBskyGraphDefsListViewTests()
        {
            // TODO uncomment below to create an instance of AppBskyGraphDefsListView
            //instance = new AppBskyGraphDefsListView();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyGraphDefsListView
        /// </summary>
        [Fact]
        public void AppBskyGraphDefsListViewInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyGraphDefsListView
            //Assert.IsType<AppBskyGraphDefsListView>(instance);
        }

        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }

        /// <summary>
        /// Test the property 'Cid'
        /// </summary>
        [Fact]
        public void CidTest()
        {
            // TODO unit test for the property 'Cid'
        }

        /// <summary>
        /// Test the property 'Creator'
        /// </summary>
        [Fact]
        public void CreatorTest()
        {
            // TODO unit test for the property 'Creator'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Purpose'
        /// </summary>
        [Fact]
        public void PurposeTest()
        {
            // TODO unit test for the property 'Purpose'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'DescriptionFacets'
        /// </summary>
        [Fact]
        public void DescriptionFacetsTest()
        {
            // TODO unit test for the property 'DescriptionFacets'
        }

        /// <summary>
        /// Test the property 'Avatar'
        /// </summary>
        [Fact]
        public void AvatarTest()
        {
            // TODO unit test for the property 'Avatar'
        }

        /// <summary>
        /// Test the property 'ListItemCount'
        /// </summary>
        [Fact]
        public void ListItemCountTest()
        {
            // TODO unit test for the property 'ListItemCount'
        }

        /// <summary>
        /// Test the property 'Labels'
        /// </summary>
        [Fact]
        public void LabelsTest()
        {
            // TODO unit test for the property 'Labels'
        }

        /// <summary>
        /// Test the property 'Viewer'
        /// </summary>
        [Fact]
        public void ViewerTest()
        {
            // TODO unit test for the property 'Viewer'
        }

        /// <summary>
        /// Test the property 'IndexedAt'
        /// </summary>
        [Fact]
        public void IndexedAtTest()
        {
            // TODO unit test for the property 'IndexedAt'
        }
    }
}
