/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyActorDefsProfileAssociated
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyActorDefsProfileAssociatedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyActorDefsProfileAssociated
        //private AppBskyActorDefsProfileAssociated instance;

        public AppBskyActorDefsProfileAssociatedTests()
        {
            // TODO uncomment below to create an instance of AppBskyActorDefsProfileAssociated
            //instance = new AppBskyActorDefsProfileAssociated();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyActorDefsProfileAssociated
        /// </summary>
        [Fact]
        public void AppBskyActorDefsProfileAssociatedInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyActorDefsProfileAssociated
            //Assert.IsType<AppBskyActorDefsProfileAssociated>(instance);
        }

        /// <summary>
        /// Test the property 'Lists'
        /// </summary>
        [Fact]
        public void ListsTest()
        {
            // TODO unit test for the property 'Lists'
        }

        /// <summary>
        /// Test the property 'Feedgens'
        /// </summary>
        [Fact]
        public void FeedgensTest()
        {
            // TODO unit test for the property 'Feedgens'
        }

        /// <summary>
        /// Test the property 'StarterPacks'
        /// </summary>
        [Fact]
        public void StarterPacksTest()
        {
            // TODO unit test for the property 'StarterPacks'
        }

        /// <summary>
        /// Test the property 'Labeler'
        /// </summary>
        [Fact]
        public void LabelerTest()
        {
            // TODO unit test for the property 'Labeler'
        }

        /// <summary>
        /// Test the property 'Chat'
        /// </summary>
        [Fact]
        public void ChatTest()
        {
            // TODO unit test for the property 'Chat'
        }
    }
}
