/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyFeedDefsReasonRepost
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyFeedDefsReasonRepostTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyFeedDefsReasonRepost
        //private AppBskyFeedDefsReasonRepost instance;

        public AppBskyFeedDefsReasonRepostTests()
        {
            // TODO uncomment below to create an instance of AppBskyFeedDefsReasonRepost
            //instance = new AppBskyFeedDefsReasonRepost();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyFeedDefsReasonRepost
        /// </summary>
        [Fact]
        public void AppBskyFeedDefsReasonRepostInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyFeedDefsReasonRepost
            //Assert.IsType<AppBskyFeedDefsReasonRepost>(instance);
        }

        /// <summary>
        /// Test the property 'By'
        /// </summary>
        [Fact]
        public void ByTest()
        {
            // TODO unit test for the property 'By'
        }

        /// <summary>
        /// Test the property 'IndexedAt'
        /// </summary>
        [Fact]
        public void IndexedAtTest()
        {
            // TODO unit test for the property 'IndexedAt'
        }
    }
}
