/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyGraphGetFollows200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyGraphGetFollows200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyGraphGetFollows200Response
        //private AppBskyGraphGetFollows200Response instance;

        public AppBskyGraphGetFollows200ResponseTests()
        {
            // TODO uncomment below to create an instance of AppBskyGraphGetFollows200Response
            //instance = new AppBskyGraphGetFollows200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyGraphGetFollows200Response
        /// </summary>
        [Fact]
        public void AppBskyGraphGetFollows200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyGraphGetFollows200Response
            //Assert.IsType<AppBskyGraphGetFollows200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }

        /// <summary>
        /// Test the property 'Cursor'
        /// </summary>
        [Fact]
        public void CursorTest()
        {
            // TODO unit test for the property 'Cursor'
        }

        /// <summary>
        /// Test the property 'Follows'
        /// </summary>
        [Fact]
        public void FollowsTest()
        {
            // TODO unit test for the property 'Follows'
        }
    }
}
