/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyNotificationPutPreferencesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyNotificationPutPreferencesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyNotificationPutPreferencesRequest
        //private AppBskyNotificationPutPreferencesRequest instance;

        public AppBskyNotificationPutPreferencesRequestTests()
        {
            // TODO uncomment below to create an instance of AppBskyNotificationPutPreferencesRequest
            //instance = new AppBskyNotificationPutPreferencesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyNotificationPutPreferencesRequest
        /// </summary>
        [Fact]
        public void AppBskyNotificationPutPreferencesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyNotificationPutPreferencesRequest
            //Assert.IsType<AppBskyNotificationPutPreferencesRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Fact]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
    }
}
