/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyActorDefsViewerState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyActorDefsViewerStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyActorDefsViewerState
        //private AppBskyActorDefsViewerState instance;

        public AppBskyActorDefsViewerStateTests()
        {
            // TODO uncomment below to create an instance of AppBskyActorDefsViewerState
            //instance = new AppBskyActorDefsViewerState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyActorDefsViewerState
        /// </summary>
        [Fact]
        public void AppBskyActorDefsViewerStateInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyActorDefsViewerState
            //Assert.IsType<AppBskyActorDefsViewerState>(instance);
        }

        /// <summary>
        /// Test the property 'Muted'
        /// </summary>
        [Fact]
        public void MutedTest()
        {
            // TODO unit test for the property 'Muted'
        }

        /// <summary>
        /// Test the property 'MutedByList'
        /// </summary>
        [Fact]
        public void MutedByListTest()
        {
            // TODO unit test for the property 'MutedByList'
        }

        /// <summary>
        /// Test the property 'BlockedBy'
        /// </summary>
        [Fact]
        public void BlockedByTest()
        {
            // TODO unit test for the property 'BlockedBy'
        }

        /// <summary>
        /// Test the property 'Blocking'
        /// </summary>
        [Fact]
        public void BlockingTest()
        {
            // TODO unit test for the property 'Blocking'
        }

        /// <summary>
        /// Test the property 'BlockingByList'
        /// </summary>
        [Fact]
        public void BlockingByListTest()
        {
            // TODO unit test for the property 'BlockingByList'
        }

        /// <summary>
        /// Test the property 'Following'
        /// </summary>
        [Fact]
        public void FollowingTest()
        {
            // TODO unit test for the property 'Following'
        }

        /// <summary>
        /// Test the property 'FollowedBy'
        /// </summary>
        [Fact]
        public void FollowedByTest()
        {
            // TODO unit test for the property 'FollowedBy'
        }

        /// <summary>
        /// Test the property 'KnownFollowers'
        /// </summary>
        [Fact]
        public void KnownFollowersTest()
        {
            // TODO unit test for the property 'KnownFollowers'
        }
    }
}
