/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyFeedDefsThreadgateView
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyFeedDefsThreadgateViewTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyFeedDefsThreadgateView
        //private AppBskyFeedDefsThreadgateView instance;

        public AppBskyFeedDefsThreadgateViewTests()
        {
            // TODO uncomment below to create an instance of AppBskyFeedDefsThreadgateView
            //instance = new AppBskyFeedDefsThreadgateView();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyFeedDefsThreadgateView
        /// </summary>
        [Fact]
        public void AppBskyFeedDefsThreadgateViewInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyFeedDefsThreadgateView
            //Assert.IsType<AppBskyFeedDefsThreadgateView>(instance);
        }

        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }

        /// <summary>
        /// Test the property 'Cid'
        /// </summary>
        [Fact]
        public void CidTest()
        {
            // TODO unit test for the property 'Cid'
        }

        /// <summary>
        /// Test the property 'Record'
        /// </summary>
        [Fact]
        public void RecordTest()
        {
            // TODO unit test for the property 'Record'
        }

        /// <summary>
        /// Test the property 'Lists'
        /// </summary>
        [Fact]
        public void ListsTest()
        {
            // TODO unit test for the property 'Lists'
        }
    }
}
