/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyVideoDefsJobStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyVideoDefsJobStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyVideoDefsJobStatus
        //private AppBskyVideoDefsJobStatus instance;

        public AppBskyVideoDefsJobStatusTests()
        {
            // TODO uncomment below to create an instance of AppBskyVideoDefsJobStatus
            //instance = new AppBskyVideoDefsJobStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyVideoDefsJobStatus
        /// </summary>
        [Fact]
        public void AppBskyVideoDefsJobStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyVideoDefsJobStatus
            //Assert.IsType<AppBskyVideoDefsJobStatus>(instance);
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }

        /// <summary>
        /// Test the property 'Did'
        /// </summary>
        [Fact]
        public void DidTest()
        {
            // TODO unit test for the property 'Did'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Progress'
        /// </summary>
        [Fact]
        public void ProgressTest()
        {
            // TODO unit test for the property 'Progress'
        }

        /// <summary>
        /// Test the property 'Blob'
        /// </summary>
        [Fact]
        public void BlobTest()
        {
            // TODO unit test for the property 'Blob'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
