/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyFeedGetLikes200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyFeedGetLikes200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyFeedGetLikes200Response
        //private AppBskyFeedGetLikes200Response instance;

        public AppBskyFeedGetLikes200ResponseTests()
        {
            // TODO uncomment below to create an instance of AppBskyFeedGetLikes200Response
            //instance = new AppBskyFeedGetLikes200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyFeedGetLikes200Response
        /// </summary>
        [Fact]
        public void AppBskyFeedGetLikes200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyFeedGetLikes200Response
            //Assert.IsType<AppBskyFeedGetLikes200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }

        /// <summary>
        /// Test the property 'Cid'
        /// </summary>
        [Fact]
        public void CidTest()
        {
            // TODO unit test for the property 'Cid'
        }

        /// <summary>
        /// Test the property 'Cursor'
        /// </summary>
        [Fact]
        public void CursorTest()
        {
            // TODO unit test for the property 'Cursor'
        }

        /// <summary>
        /// Test the property 'Likes'
        /// </summary>
        [Fact]
        public void LikesTest()
        {
            // TODO unit test for the property 'Likes'
        }
    }
}
