/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyGraphDefsNotFoundActor
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyGraphDefsNotFoundActorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyGraphDefsNotFoundActor
        //private AppBskyGraphDefsNotFoundActor instance;

        public AppBskyGraphDefsNotFoundActorTests()
        {
            // TODO uncomment below to create an instance of AppBskyGraphDefsNotFoundActor
            //instance = new AppBskyGraphDefsNotFoundActor();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyGraphDefsNotFoundActor
        /// </summary>
        [Fact]
        public void AppBskyGraphDefsNotFoundActorInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyGraphDefsNotFoundActor
            //Assert.IsType<AppBskyGraphDefsNotFoundActor>(instance);
        }

        /// <summary>
        /// Test the property 'Actor'
        /// </summary>
        [Fact]
        public void ActorTest()
        {
            // TODO unit test for the property 'Actor'
        }

        /// <summary>
        /// Test the property 'NotFound'
        /// </summary>
        [Fact]
        public void NotFoundTest()
        {
            // TODO unit test for the property 'NotFound'
        }
    }
}
