/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing AppBskyGraphGetStarterPack200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppBskyGraphGetStarterPack200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppBskyGraphGetStarterPack200Response
        //private AppBskyGraphGetStarterPack200Response instance;

        public AppBskyGraphGetStarterPack200ResponseTests()
        {
            // TODO uncomment below to create an instance of AppBskyGraphGetStarterPack200Response
            //instance = new AppBskyGraphGetStarterPack200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyGraphGetStarterPack200Response
        /// </summary>
        [Fact]
        public void AppBskyGraphGetStarterPack200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppBskyGraphGetStarterPack200Response
            //Assert.IsType<AppBskyGraphGetStarterPack200Response>(instance);
        }

        /// <summary>
        /// Test the property 'StarterPack'
        /// </summary>
        [Fact]
        public void StarterPackTest()
        {
            // TODO unit test for the property 'StarterPack'
        }
    }
}
