/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing ChatBskyConvoUpdateReadRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChatBskyConvoUpdateReadRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChatBskyConvoUpdateReadRequest
        //private ChatBskyConvoUpdateReadRequest instance;

        public ChatBskyConvoUpdateReadRequestTests()
        {
            // TODO uncomment below to create an instance of ChatBskyConvoUpdateReadRequest
            //instance = new ChatBskyConvoUpdateReadRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChatBskyConvoUpdateReadRequest
        /// </summary>
        [Fact]
        public void ChatBskyConvoUpdateReadRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChatBskyConvoUpdateReadRequest
            //Assert.IsType<ChatBskyConvoUpdateReadRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ConvoId'
        /// </summary>
        [Fact]
        public void ConvoIdTest()
        {
            // TODO unit test for the property 'ConvoId'
        }

        /// <summary>
        /// Test the property 'MessageId'
        /// </summary>
        [Fact]
        public void MessageIdTest()
        {
            // TODO unit test for the property 'MessageId'
        }
    }
}
