/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing ChatBskyConvoDefsMessageView
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChatBskyConvoDefsMessageViewTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChatBskyConvoDefsMessageView
        //private ChatBskyConvoDefsMessageView instance;

        public ChatBskyConvoDefsMessageViewTests()
        {
            // TODO uncomment below to create an instance of ChatBskyConvoDefsMessageView
            //instance = new ChatBskyConvoDefsMessageView();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChatBskyConvoDefsMessageView
        /// </summary>
        [Fact]
        public void ChatBskyConvoDefsMessageViewInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChatBskyConvoDefsMessageView
            //Assert.IsType<ChatBskyConvoDefsMessageView>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Rev'
        /// </summary>
        [Fact]
        public void RevTest()
        {
            // TODO unit test for the property 'Rev'
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'Facets'
        /// </summary>
        [Fact]
        public void FacetsTest()
        {
            // TODO unit test for the property 'Facets'
        }

        /// <summary>
        /// Test the property 'Embed'
        /// </summary>
        [Fact]
        public void EmbedTest()
        {
            // TODO unit test for the property 'Embed'
        }

        /// <summary>
        /// Test the property 'Sender'
        /// </summary>
        [Fact]
        public void SenderTest()
        {
            // TODO unit test for the property 'Sender'
        }

        /// <summary>
        /// Test the property 'SentAt'
        /// </summary>
        [Fact]
        public void SentAtTest()
        {
            // TODO unit test for the property 'SentAt'
        }
    }
}
