/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing ChatBskyActorDefsProfileViewBasic
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChatBskyActorDefsProfileViewBasicTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChatBskyActorDefsProfileViewBasic
        //private ChatBskyActorDefsProfileViewBasic instance;

        public ChatBskyActorDefsProfileViewBasicTests()
        {
            // TODO uncomment below to create an instance of ChatBskyActorDefsProfileViewBasic
            //instance = new ChatBskyActorDefsProfileViewBasic();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChatBskyActorDefsProfileViewBasic
        /// </summary>
        [Fact]
        public void ChatBskyActorDefsProfileViewBasicInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChatBskyActorDefsProfileViewBasic
            //Assert.IsType<ChatBskyActorDefsProfileViewBasic>(instance);
        }

        /// <summary>
        /// Test the property 'Did'
        /// </summary>
        [Fact]
        public void DidTest()
        {
            // TODO unit test for the property 'Did'
        }

        /// <summary>
        /// Test the property 'Handle'
        /// </summary>
        [Fact]
        public void HandleTest()
        {
            // TODO unit test for the property 'Handle'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }

        /// <summary>
        /// Test the property 'Avatar'
        /// </summary>
        [Fact]
        public void AvatarTest()
        {
            // TODO unit test for the property 'Avatar'
        }

        /// <summary>
        /// Test the property 'Associated'
        /// </summary>
        [Fact]
        public void AssociatedTest()
        {
            // TODO unit test for the property 'Associated'
        }

        /// <summary>
        /// Test the property 'Viewer'
        /// </summary>
        [Fact]
        public void ViewerTest()
        {
            // TODO unit test for the property 'Viewer'
        }

        /// <summary>
        /// Test the property 'Labels'
        /// </summary>
        [Fact]
        public void LabelsTest()
        {
            // TODO unit test for the property 'Labels'
        }

        /// <summary>
        /// Test the property 'ChatDisabled'
        /// </summary>
        [Fact]
        public void ChatDisabledTest()
        {
            // TODO unit test for the property 'ChatDisabled'
        }
    }
}
