/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing ChatBskyModerationUpdateActorAccessRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChatBskyModerationUpdateActorAccessRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChatBskyModerationUpdateActorAccessRequest
        //private ChatBskyModerationUpdateActorAccessRequest instance;

        public ChatBskyModerationUpdateActorAccessRequestTests()
        {
            // TODO uncomment below to create an instance of ChatBskyModerationUpdateActorAccessRequest
            //instance = new ChatBskyModerationUpdateActorAccessRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChatBskyModerationUpdateActorAccessRequest
        /// </summary>
        [Fact]
        public void ChatBskyModerationUpdateActorAccessRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChatBskyModerationUpdateActorAccessRequest
            //Assert.IsType<ChatBskyModerationUpdateActorAccessRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Actor'
        /// </summary>
        [Fact]
        public void ActorTest()
        {
            // TODO unit test for the property 'Actor'
        }

        /// <summary>
        /// Test the property 'AllowAccess'
        /// </summary>
        [Fact]
        public void AllowAccessTest()
        {
            // TODO unit test for the property 'AllowAccess'
        }

        /// <summary>
        /// Test the property 'Ref'
        /// </summary>
        [Fact]
        public void RefTest()
        {
            // TODO unit test for the property 'Ref'
        }
    }
}
