/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing ChatBskyModerationGetActorMetadataMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChatBskyModerationGetActorMetadataMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChatBskyModerationGetActorMetadataMetadata
        //private ChatBskyModerationGetActorMetadataMetadata instance;

        public ChatBskyModerationGetActorMetadataMetadataTests()
        {
            // TODO uncomment below to create an instance of ChatBskyModerationGetActorMetadataMetadata
            //instance = new ChatBskyModerationGetActorMetadataMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChatBskyModerationGetActorMetadataMetadata
        /// </summary>
        [Fact]
        public void ChatBskyModerationGetActorMetadataMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChatBskyModerationGetActorMetadataMetadata
            //Assert.IsType<ChatBskyModerationGetActorMetadataMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'MessagesSent'
        /// </summary>
        [Fact]
        public void MessagesSentTest()
        {
            // TODO unit test for the property 'MessagesSent'
        }

        /// <summary>
        /// Test the property 'MessagesReceived'
        /// </summary>
        [Fact]
        public void MessagesReceivedTest()
        {
            // TODO unit test for the property 'MessagesReceived'
        }

        /// <summary>
        /// Test the property 'Convos'
        /// </summary>
        [Fact]
        public void ConvosTest()
        {
            // TODO unit test for the property 'Convos'
        }

        /// <summary>
        /// Test the property 'ConvosStarted'
        /// </summary>
        [Fact]
        public void ConvosStartedTest()
        {
            // TODO unit test for the property 'ConvosStarted'
        }
    }
}
