/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing ChatBskyConvoDefsLogDeleteMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChatBskyConvoDefsLogDeleteMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChatBskyConvoDefsLogDeleteMessage
        //private ChatBskyConvoDefsLogDeleteMessage instance;

        public ChatBskyConvoDefsLogDeleteMessageTests()
        {
            // TODO uncomment below to create an instance of ChatBskyConvoDefsLogDeleteMessage
            //instance = new ChatBskyConvoDefsLogDeleteMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChatBskyConvoDefsLogDeleteMessage
        /// </summary>
        [Fact]
        public void ChatBskyConvoDefsLogDeleteMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChatBskyConvoDefsLogDeleteMessage
            //Assert.IsType<ChatBskyConvoDefsLogDeleteMessage>(instance);
        }

        /// <summary>
        /// Test the property 'Rev'
        /// </summary>
        [Fact]
        public void RevTest()
        {
            // TODO unit test for the property 'Rev'
        }

        /// <summary>
        /// Test the property 'ConvoId'
        /// </summary>
        [Fact]
        public void ConvoIdTest()
        {
            // TODO unit test for the property 'ConvoId'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
