/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing ComAtprotoAdminSendEmail200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComAtprotoAdminSendEmail200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ComAtprotoAdminSendEmail200Response
        //private ComAtprotoAdminSendEmail200Response instance;

        public ComAtprotoAdminSendEmail200ResponseTests()
        {
            // TODO uncomment below to create an instance of ComAtprotoAdminSendEmail200Response
            //instance = new ComAtprotoAdminSendEmail200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComAtprotoAdminSendEmail200Response
        /// </summary>
        [Fact]
        public void ComAtprotoAdminSendEmail200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ComAtprotoAdminSendEmail200Response
            //Assert.IsType<ComAtprotoAdminSendEmail200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Sent'
        /// </summary>
        [Fact]
        public void SentTest()
        {
            // TODO unit test for the property 'Sent'
        }
    }
}
