/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing ComAtprotoServerDeleteAccountRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComAtprotoServerDeleteAccountRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ComAtprotoServerDeleteAccountRequest
        //private ComAtprotoServerDeleteAccountRequest instance;

        public ComAtprotoServerDeleteAccountRequestTests()
        {
            // TODO uncomment below to create an instance of ComAtprotoServerDeleteAccountRequest
            //instance = new ComAtprotoServerDeleteAccountRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComAtprotoServerDeleteAccountRequest
        /// </summary>
        [Fact]
        public void ComAtprotoServerDeleteAccountRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ComAtprotoServerDeleteAccountRequest
            //Assert.IsType<ComAtprotoServerDeleteAccountRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Did'
        /// </summary>
        [Fact]
        public void DidTest()
        {
            // TODO unit test for the property 'Did'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
    }
}
