/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing ComAtprotoAdminUpdateAccountEmailRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComAtprotoAdminUpdateAccountEmailRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ComAtprotoAdminUpdateAccountEmailRequest
        //private ComAtprotoAdminUpdateAccountEmailRequest instance;

        public ComAtprotoAdminUpdateAccountEmailRequestTests()
        {
            // TODO uncomment below to create an instance of ComAtprotoAdminUpdateAccountEmailRequest
            //instance = new ComAtprotoAdminUpdateAccountEmailRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComAtprotoAdminUpdateAccountEmailRequest
        /// </summary>
        [Fact]
        public void ComAtprotoAdminUpdateAccountEmailRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ComAtprotoAdminUpdateAccountEmailRequest
            //Assert.IsType<ComAtprotoAdminUpdateAccountEmailRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
    }
}
