/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing ComAtprotoSyncGetLatestCommit200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComAtprotoSyncGetLatestCommit200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ComAtprotoSyncGetLatestCommit200Response
        //private ComAtprotoSyncGetLatestCommit200Response instance;

        public ComAtprotoSyncGetLatestCommit200ResponseTests()
        {
            // TODO uncomment below to create an instance of ComAtprotoSyncGetLatestCommit200Response
            //instance = new ComAtprotoSyncGetLatestCommit200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComAtprotoSyncGetLatestCommit200Response
        /// </summary>
        [Fact]
        public void ComAtprotoSyncGetLatestCommit200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ComAtprotoSyncGetLatestCommit200Response
            //Assert.IsType<ComAtprotoSyncGetLatestCommit200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Cid'
        /// </summary>
        [Fact]
        public void CidTest()
        {
            // TODO unit test for the property 'Cid'
        }

        /// <summary>
        /// Test the property 'Rev'
        /// </summary>
        [Fact]
        public void RevTest()
        {
            // TODO unit test for the property 'Rev'
        }
    }
}
