/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing ComAtprotoSyncSubscribeReposRepoOp
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComAtprotoSyncSubscribeReposRepoOpTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ComAtprotoSyncSubscribeReposRepoOp
        //private ComAtprotoSyncSubscribeReposRepoOp instance;

        public ComAtprotoSyncSubscribeReposRepoOpTests()
        {
            // TODO uncomment below to create an instance of ComAtprotoSyncSubscribeReposRepoOp
            //instance = new ComAtprotoSyncSubscribeReposRepoOp();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComAtprotoSyncSubscribeReposRepoOp
        /// </summary>
        [Fact]
        public void ComAtprotoSyncSubscribeReposRepoOpInstanceTest()
        {
            // TODO uncomment below to test "IsType" ComAtprotoSyncSubscribeReposRepoOp
            //Assert.IsType<ComAtprotoSyncSubscribeReposRepoOp>(instance);
        }

        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

        /// <summary>
        /// Test the property 'Cid'
        /// </summary>
        [Fact]
        public void CidTest()
        {
            // TODO unit test for the property 'Cid'
        }
    }
}
