/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing ComAtprotoIdentityGetRecommendedDidCredentials200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComAtprotoIdentityGetRecommendedDidCredentials200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ComAtprotoIdentityGetRecommendedDidCredentials200Response
        //private ComAtprotoIdentityGetRecommendedDidCredentials200Response instance;

        public ComAtprotoIdentityGetRecommendedDidCredentials200ResponseTests()
        {
            // TODO uncomment below to create an instance of ComAtprotoIdentityGetRecommendedDidCredentials200Response
            //instance = new ComAtprotoIdentityGetRecommendedDidCredentials200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComAtprotoIdentityGetRecommendedDidCredentials200Response
        /// </summary>
        [Fact]
        public void ComAtprotoIdentityGetRecommendedDidCredentials200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ComAtprotoIdentityGetRecommendedDidCredentials200Response
            //Assert.IsType<ComAtprotoIdentityGetRecommendedDidCredentials200Response>(instance);
        }

        /// <summary>
        /// Test the property 'RotationKeys'
        /// </summary>
        [Fact]
        public void RotationKeysTest()
        {
            // TODO unit test for the property 'RotationKeys'
        }

        /// <summary>
        /// Test the property 'AlsoKnownAs'
        /// </summary>
        [Fact]
        public void AlsoKnownAsTest()
        {
            // TODO unit test for the property 'AlsoKnownAs'
        }

        /// <summary>
        /// Test the property 'VerificationMethods'
        /// </summary>
        [Fact]
        public void VerificationMethodsTest()
        {
            // TODO unit test for the property 'VerificationMethods'
        }

        /// <summary>
        /// Test the property 'Services'
        /// </summary>
        [Fact]
        public void ServicesTest()
        {
            // TODO unit test for the property 'Services'
        }
    }
}
