/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing ComAtprotoRepoCreateRecord200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComAtprotoRepoCreateRecord200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ComAtprotoRepoCreateRecord200Response
        //private ComAtprotoRepoCreateRecord200Response instance;

        public ComAtprotoRepoCreateRecord200ResponseTests()
        {
            // TODO uncomment below to create an instance of ComAtprotoRepoCreateRecord200Response
            //instance = new ComAtprotoRepoCreateRecord200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComAtprotoRepoCreateRecord200Response
        /// </summary>
        [Fact]
        public void ComAtprotoRepoCreateRecord200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ComAtprotoRepoCreateRecord200Response
            //Assert.IsType<ComAtprotoRepoCreateRecord200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }

        /// <summary>
        /// Test the property 'Cid'
        /// </summary>
        [Fact]
        public void CidTest()
        {
            // TODO unit test for the property 'Cid'
        }

        /// <summary>
        /// Test the property 'Commit'
        /// </summary>
        [Fact]
        public void CommitTest()
        {
            // TODO unit test for the property 'Commit'
        }

        /// <summary>
        /// Test the property 'ValidationStatus'
        /// </summary>
        [Fact]
        public void ValidationStatusTest()
        {
            // TODO unit test for the property 'ValidationStatus'
        }
    }
}
