/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing ToolsOzoneModerationDefsRecordViewNotFound
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ToolsOzoneModerationDefsRecordViewNotFoundTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ToolsOzoneModerationDefsRecordViewNotFound
        //private ToolsOzoneModerationDefsRecordViewNotFound instance;

        public ToolsOzoneModerationDefsRecordViewNotFoundTests()
        {
            // TODO uncomment below to create an instance of ToolsOzoneModerationDefsRecordViewNotFound
            //instance = new ToolsOzoneModerationDefsRecordViewNotFound();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ToolsOzoneModerationDefsRecordViewNotFound
        /// </summary>
        [Fact]
        public void ToolsOzoneModerationDefsRecordViewNotFoundInstanceTest()
        {
            // TODO uncomment below to test "IsType" ToolsOzoneModerationDefsRecordViewNotFound
            //Assert.IsType<ToolsOzoneModerationDefsRecordViewNotFound>(instance);
        }

        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
    }
}
