/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing ToolsOzoneCommunicationDefsTemplateView
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ToolsOzoneCommunicationDefsTemplateViewTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ToolsOzoneCommunicationDefsTemplateView
        //private ToolsOzoneCommunicationDefsTemplateView instance;

        public ToolsOzoneCommunicationDefsTemplateViewTests()
        {
            // TODO uncomment below to create an instance of ToolsOzoneCommunicationDefsTemplateView
            //instance = new ToolsOzoneCommunicationDefsTemplateView();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ToolsOzoneCommunicationDefsTemplateView
        /// </summary>
        [Fact]
        public void ToolsOzoneCommunicationDefsTemplateViewInstanceTest()
        {
            // TODO uncomment below to test "IsType" ToolsOzoneCommunicationDefsTemplateView
            //Assert.IsType<ToolsOzoneCommunicationDefsTemplateView>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }

        /// <summary>
        /// Test the property 'ContentMarkdown'
        /// </summary>
        [Fact]
        public void ContentMarkdownTest()
        {
            // TODO unit test for the property 'ContentMarkdown'
        }

        /// <summary>
        /// Test the property 'Disabled'
        /// </summary>
        [Fact]
        public void DisabledTest()
        {
            // TODO unit test for the property 'Disabled'
        }

        /// <summary>
        /// Test the property 'Lang'
        /// </summary>
        [Fact]
        public void LangTest()
        {
            // TODO unit test for the property 'Lang'
        }

        /// <summary>
        /// Test the property 'LastUpdatedBy'
        /// </summary>
        [Fact]
        public void LastUpdatedByTest()
        {
            // TODO unit test for the property 'LastUpdatedBy'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
