/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BSky.Model;
using BSky.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BSky.Test.Model
{
    /// <summary>
    ///  Class for testing ToolsOzoneModerationDefsModEventComment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ToolsOzoneModerationDefsModEventCommentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ToolsOzoneModerationDefsModEventComment
        //private ToolsOzoneModerationDefsModEventComment instance;

        public ToolsOzoneModerationDefsModEventCommentTests()
        {
            // TODO uncomment below to create an instance of ToolsOzoneModerationDefsModEventComment
            //instance = new ToolsOzoneModerationDefsModEventComment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ToolsOzoneModerationDefsModEventComment
        /// </summary>
        [Fact]
        public void ToolsOzoneModerationDefsModEventCommentInstanceTest()
        {
            // TODO uncomment below to test "IsType" ToolsOzoneModerationDefsModEventComment
            //Assert.IsType<ToolsOzoneModerationDefsModEventComment>(instance);
        }

        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Fact]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }

        /// <summary>
        /// Test the property 'Sticky'
        /// </summary>
        [Fact]
        public void StickyTest()
        {
            // TODO unit test for the property 'Sticky'
        }
    }
}
