/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using BSky.Client;
using BSky.Api;
// uncomment below to import models
//using BSky.Model;

namespace BSky.Test.Api
{
    /// <summary>
    ///  Class for testing AppBskyFeedApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AppBskyFeedApiTests : IDisposable
    {
        private AppBskyFeedApi instance;

        public AppBskyFeedApiTests()
        {
            instance = new AppBskyFeedApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppBskyFeedApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AppBskyFeedApi
            //Assert.IsType<AppBskyFeedApi>(instance);
        }

        /// <summary>
        /// Test AppBskyFeedDescribeFeedGenerator
        /// </summary>
        [Fact]
        public void AppBskyFeedDescribeFeedGeneratorTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.AppBskyFeedDescribeFeedGenerator();
            //Assert.IsType<AppBskyFeedDescribeFeedGenerator200Response>(response);
        }

        /// <summary>
        /// Test AppBskyFeedGetActorFeeds
        /// </summary>
        [Fact]
        public void AppBskyFeedGetActorFeedsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string actor = null;
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyFeedGetActorFeeds(actor, limit, cursor);
            //Assert.IsType<AppBskyFeedGetActorFeeds200Response>(response);
        }

        /// <summary>
        /// Test AppBskyFeedGetActorLikes
        /// </summary>
        [Fact]
        public void AppBskyFeedGetActorLikesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string actor = null;
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyFeedGetActorLikes(actor, limit, cursor);
            //Assert.IsType<AppBskyFeedGetActorLikes200Response>(response);
        }

        /// <summary>
        /// Test AppBskyFeedGetAuthorFeed
        /// </summary>
        [Fact]
        public void AppBskyFeedGetAuthorFeedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string actor = null;
            //int? limit = null;
            //string? cursor = null;
            //string? filter = null;
            //var response = instance.AppBskyFeedGetAuthorFeed(actor, limit, cursor, filter);
            //Assert.IsType<AppBskyFeedGetActorLikes200Response>(response);
        }

        /// <summary>
        /// Test AppBskyFeedGetFeed
        /// </summary>
        [Fact]
        public void AppBskyFeedGetFeedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string feed = null;
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyFeedGetFeed(feed, limit, cursor);
            //Assert.IsType<AppBskyFeedGetActorLikes200Response>(response);
        }

        /// <summary>
        /// Test AppBskyFeedGetFeedGenerator
        /// </summary>
        [Fact]
        public void AppBskyFeedGetFeedGeneratorTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string feed = null;
            //var response = instance.AppBskyFeedGetFeedGenerator(feed);
            //Assert.IsType<AppBskyFeedGetFeedGenerator200Response>(response);
        }

        /// <summary>
        /// Test AppBskyFeedGetFeedGenerators
        /// </summary>
        [Fact]
        public void AppBskyFeedGetFeedGeneratorsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> feeds = null;
            //var response = instance.AppBskyFeedGetFeedGenerators(feeds);
            //Assert.IsType<AppBskyFeedGetFeedGenerators200Response>(response);
        }

        /// <summary>
        /// Test AppBskyFeedGetFeedSkeleton
        /// </summary>
        [Fact]
        public void AppBskyFeedGetFeedSkeletonTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string feed = null;
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyFeedGetFeedSkeleton(feed, limit, cursor);
            //Assert.IsType<AppBskyFeedGetFeedSkeleton200Response>(response);
        }

        /// <summary>
        /// Test AppBskyFeedGetLikes
        /// </summary>
        [Fact]
        public void AppBskyFeedGetLikesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uri = null;
            //string? cid = null;
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyFeedGetLikes(uri, cid, limit, cursor);
            //Assert.IsType<AppBskyFeedGetLikes200Response>(response);
        }

        /// <summary>
        /// Test AppBskyFeedGetListFeed
        /// </summary>
        [Fact]
        public void AppBskyFeedGetListFeedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string list = null;
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyFeedGetListFeed(list, limit, cursor);
            //Assert.IsType<AppBskyFeedGetActorLikes200Response>(response);
        }

        /// <summary>
        /// Test AppBskyFeedGetPostThread
        /// </summary>
        [Fact]
        public void AppBskyFeedGetPostThreadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uri = null;
            //int? depth = null;
            //int? parentHeight = null;
            //var response = instance.AppBskyFeedGetPostThread(uri, depth, parentHeight);
            //Assert.IsType<AppBskyFeedGetPostThread200Response>(response);
        }

        /// <summary>
        /// Test AppBskyFeedGetPosts
        /// </summary>
        [Fact]
        public void AppBskyFeedGetPostsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> uris = null;
            //var response = instance.AppBskyFeedGetPosts(uris);
            //Assert.IsType<AppBskyFeedGetPosts200Response>(response);
        }

        /// <summary>
        /// Test AppBskyFeedGetQuotes
        /// </summary>
        [Fact]
        public void AppBskyFeedGetQuotesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uri = null;
            //string? cid = null;
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyFeedGetQuotes(uri, cid, limit, cursor);
            //Assert.IsType<AppBskyFeedGetQuotes200Response>(response);
        }

        /// <summary>
        /// Test AppBskyFeedGetRepostedBy
        /// </summary>
        [Fact]
        public void AppBskyFeedGetRepostedByTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uri = null;
            //string? cid = null;
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyFeedGetRepostedBy(uri, cid, limit, cursor);
            //Assert.IsType<AppBskyFeedGetRepostedBy200Response>(response);
        }

        /// <summary>
        /// Test AppBskyFeedGetSuggestedFeeds
        /// </summary>
        [Fact]
        public void AppBskyFeedGetSuggestedFeedsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyFeedGetSuggestedFeeds(limit, cursor);
            //Assert.IsType<AppBskyFeedGetActorFeeds200Response>(response);
        }

        /// <summary>
        /// Test AppBskyFeedGetTimeline
        /// </summary>
        [Fact]
        public void AppBskyFeedGetTimelineTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? algorithm = null;
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyFeedGetTimeline(algorithm, limit, cursor);
            //Assert.IsType<AppBskyFeedGetActorLikes200Response>(response);
        }

        /// <summary>
        /// Test AppBskyFeedSearchPosts
        /// </summary>
        [Fact]
        public void AppBskyFeedSearchPostsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string q = null;
            //string? sort = null;
            //string? since = null;
            //string? until = null;
            //string? mentions = null;
            //string? author = null;
            //string? lang = null;
            //string? domain = null;
            //string? url = null;
            //List<string>? tag = null;
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.AppBskyFeedSearchPosts(q, sort, since, until, mentions, author, lang, domain, url, tag, limit, cursor);
            //Assert.IsType<AppBskyFeedSearchPosts200Response>(response);
        }

        /// <summary>
        /// Test AppBskyFeedSendInteractions
        /// </summary>
        [Fact]
        public void AppBskyFeedSendInteractionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AppBskyFeedSendInteractionsRequest appBskyFeedSendInteractionsRequest = null;
            //var response = instance.AppBskyFeedSendInteractions(appBskyFeedSendInteractionsRequest);
            //Assert.IsType<AppBskyFeedSendInteractions200Response>(response);
        }
    }
}
