/*
 * AT Protocol XRPC API
 *
 * This section contains HTTP API reference docs for Bluesky and AT Protocol lexicons. Generate a bearer token to test API calls directly from the docs.
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using BSky.Client;
using BSky.Api;
// uncomment below to import models
//using BSky.Model;

namespace BSky.Test.Api
{
    /// <summary>
    ///  Class for testing ComAtprotoAdminApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ComAtprotoAdminApiTests : IDisposable
    {
        private ComAtprotoAdminApi instance;

        public ComAtprotoAdminApiTests()
        {
            instance = new ComAtprotoAdminApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComAtprotoAdminApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ComAtprotoAdminApi
            //Assert.IsType<ComAtprotoAdminApi>(instance);
        }

        /// <summary>
        /// Test ComAtprotoAdminDeleteAccount
        /// </summary>
        [Fact]
        public void ComAtprotoAdminDeleteAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ComAtprotoAdminDeleteAccountRequest comAtprotoAdminDeleteAccountRequest = null;
            //instance.ComAtprotoAdminDeleteAccount(comAtprotoAdminDeleteAccountRequest);
        }

        /// <summary>
        /// Test ComAtprotoAdminDisableAccountInvites
        /// </summary>
        [Fact]
        public void ComAtprotoAdminDisableAccountInvitesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ComAtprotoAdminDisableAccountInvitesRequest comAtprotoAdminDisableAccountInvitesRequest = null;
            //instance.ComAtprotoAdminDisableAccountInvites(comAtprotoAdminDisableAccountInvitesRequest);
        }

        /// <summary>
        /// Test ComAtprotoAdminDisableInviteCodes
        /// </summary>
        [Fact]
        public void ComAtprotoAdminDisableInviteCodesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ComAtprotoAdminDisableInviteCodesRequest comAtprotoAdminDisableInviteCodesRequest = null;
            //instance.ComAtprotoAdminDisableInviteCodes(comAtprotoAdminDisableInviteCodesRequest);
        }

        /// <summary>
        /// Test ComAtprotoAdminEnableAccountInvites
        /// </summary>
        [Fact]
        public void ComAtprotoAdminEnableAccountInvitesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ComAtprotoAdminEnableAccountInvitesRequest comAtprotoAdminEnableAccountInvitesRequest = null;
            //instance.ComAtprotoAdminEnableAccountInvites(comAtprotoAdminEnableAccountInvitesRequest);
        }

        /// <summary>
        /// Test ComAtprotoAdminGetAccountInfo
        /// </summary>
        [Fact]
        public void ComAtprotoAdminGetAccountInfoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string did = null;
            //var response = instance.ComAtprotoAdminGetAccountInfo(did);
            //Assert.IsType<ComAtprotoAdminDefsAccountView>(response);
        }

        /// <summary>
        /// Test ComAtprotoAdminGetAccountInfos
        /// </summary>
        [Fact]
        public void ComAtprotoAdminGetAccountInfosTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> dids = null;
            //var response = instance.ComAtprotoAdminGetAccountInfos(dids);
            //Assert.IsType<ComAtprotoAdminGetAccountInfos200Response>(response);
        }

        /// <summary>
        /// Test ComAtprotoAdminGetInviteCodes
        /// </summary>
        [Fact]
        public void ComAtprotoAdminGetInviteCodesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? sort = null;
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.ComAtprotoAdminGetInviteCodes(sort, limit, cursor);
            //Assert.IsType<ComAtprotoAdminGetInviteCodes200Response>(response);
        }

        /// <summary>
        /// Test ComAtprotoAdminGetSubjectStatus
        /// </summary>
        [Fact]
        public void ComAtprotoAdminGetSubjectStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? did = null;
            //string? uri = null;
            //string? blob = null;
            //var response = instance.ComAtprotoAdminGetSubjectStatus(did, uri, blob);
            //Assert.IsType<ComAtprotoAdminGetSubjectStatus200Response>(response);
        }

        /// <summary>
        /// Test ComAtprotoAdminSearchAccounts
        /// </summary>
        [Fact]
        public void ComAtprotoAdminSearchAccountsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? email = null;
            //string? cursor = null;
            //int? limit = null;
            //var response = instance.ComAtprotoAdminSearchAccounts(email, cursor, limit);
            //Assert.IsType<ComAtprotoAdminSearchAccounts200Response>(response);
        }

        /// <summary>
        /// Test ComAtprotoAdminSendEmail
        /// </summary>
        [Fact]
        public void ComAtprotoAdminSendEmailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ComAtprotoAdminSendEmailRequest comAtprotoAdminSendEmailRequest = null;
            //var response = instance.ComAtprotoAdminSendEmail(comAtprotoAdminSendEmailRequest);
            //Assert.IsType<ComAtprotoAdminSendEmail200Response>(response);
        }

        /// <summary>
        /// Test ComAtprotoAdminUpdateAccountEmail
        /// </summary>
        [Fact]
        public void ComAtprotoAdminUpdateAccountEmailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ComAtprotoAdminUpdateAccountEmailRequest comAtprotoAdminUpdateAccountEmailRequest = null;
            //instance.ComAtprotoAdminUpdateAccountEmail(comAtprotoAdminUpdateAccountEmailRequest);
        }

        /// <summary>
        /// Test ComAtprotoAdminUpdateAccountHandle
        /// </summary>
        [Fact]
        public void ComAtprotoAdminUpdateAccountHandleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ComAtprotoAdminUpdateAccountHandleRequest comAtprotoAdminUpdateAccountHandleRequest = null;
            //instance.ComAtprotoAdminUpdateAccountHandle(comAtprotoAdminUpdateAccountHandleRequest);
        }

        /// <summary>
        /// Test ComAtprotoAdminUpdateAccountPassword
        /// </summary>
        [Fact]
        public void ComAtprotoAdminUpdateAccountPasswordTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ComAtprotoAdminUpdateAccountPasswordRequest comAtprotoAdminUpdateAccountPasswordRequest = null;
            //instance.ComAtprotoAdminUpdateAccountPassword(comAtprotoAdminUpdateAccountPasswordRequest);
        }

        /// <summary>
        /// Test ComAtprotoAdminUpdateSubjectStatus
        /// </summary>
        [Fact]
        public void ComAtprotoAdminUpdateSubjectStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ComAtprotoAdminGetSubjectStatus200Response comAtprotoAdminGetSubjectStatus200Response = null;
            //var response = instance.ComAtprotoAdminUpdateSubjectStatus(comAtprotoAdminGetSubjectStatus200Response);
            //Assert.IsType<ComAtprotoAdminUpdateSubjectStatus200Response>(response);
        }
    }
}
